### PR TITLE
[nrf fromtree] Add support for nRF52820 and nRF5340 in direction finding

### PR DESCRIPTION
**Pull request by ppryga**
Add support for nRF52820 and nRF5340 in Bluetooth direction finding.
Update direction finding samples to enable support for SOCs mentioned above.

### CODE REVIEW

**Comment by ppryga** [comment]
Compliance failed on non-empty second line in commit messages.

**Review by cvinayak — APPROVED** [review]
QUICK-ACK. As this is from upstream tree.

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
DNM because there's no manifest update. I've requested one in https://github.com/nrfconnect/sdk-nrf/pull/4773#pullrequestreview-710815935.

**Comment by ppryga** [comment]
The PR added to west manifest in PR: https://github.com/nrfconnect/sdk-nrf/pull/4773.
If the CI is green there this PR may be merged.
Then I'll update manifest in https://github.com/nrfconnect/sdk-nrf/pull/4773 to final commit SHA.

**Review by mbolivar-nordic — APPROVED** [review]

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
Sorry @ppryga, but this did not make it in time. I've begun the upmerge procedure and so you'll have to wait for it to finish to get these patches in that way; sdk-zephyr is currently closed to non-upmerge patches.

**Comment by ppryga** [comment]
That means the PR can be closed. All commits were `[nrf fromtree]`, so they will arrive with end umperge.

**Pull request closed without merging**
