### PR TITLE
Cherry-pick LwM2M and CoAP fixes from upstream

### PR DESCRIPTION
**Pull request by SeppoTakalo**
Fetch LwM2M and CoAP related bugfixes and improvements.

### CODE REVIEW

**Comment by SeppoTakalo** [comment]
I fail to understand why compliance check failed:
```
Undefined Kconfig symbols:

 warning: undefined symbol NRF_SECURITY:

- Referenced at modules/mbedtls/Kconfig.tls-generic:14:
```
I don't think  I touched modules/mbedtls.

**Comment by SeppoTakalo** [comment]
Ah.. seem probably fixed in https://github.com/nrfconnect/sdk-zephyr/pull/1324

**Review by rlubos — APPROVED** [review]

**Review by jheiskan81 — APPROVED** [review]

**Review by de-nordic — CHANGES_REQUESTED** [review]
At least first three commits need to be dropped.
Rebease needed?

**Comment by SeppoTakalo** [comment]
@de-nordic rebased.

**Review by de-nordic — APPROVED** [review]

**Comment by SeppoTakalo** [comment]
Can we merge this?
CI seem quite happy, except the job that seem to be broken in main as well:
Screenshot from 2023-10-04 12-41-10

**Pull request merged**
