### PR TITLE
sdk-zephyr-upmerge

### PR DESCRIPTION
**Pull request by bjarki-andreasen**

### CODE REVIEW

**Comment by rlubos** [comment]
`ncs-compare` ouptut (for Zephyr) looks clean, although a few things need clarification:
* All cherry-picked commits (those on top of the merge commit) should have the same sauce tag as they had before cherry-picking.
* not all `[nrf noup]` seem to have been reapplied after merge, for instance I can't see https://github.com/bjarki-andreasen/sdk-zephyr/commit/712be3f1542fbda8be8a37a24f2a1055a33503eb
* When checking `ncs-loot` after the merge, I found a couple of problematic `[nrf fromlist]` commits: 
  - eac356d34483400ae61b7e743dcbd022e406079a - upstream PR was closed, need to clarify with @nordicjm how to proceed
  - 84b17002ec64d0ad5fc58aaa913506187934752c - same story, to clarify with @anangl

**Comment by nordicjm** [comment]
> https://github.com/nrfconnect/sdk-zephyr/commit/eac356d34483400ae61b7e743dcbd022e406079a - upstream PR was closed, need to clarify with @nordicjm how to proceed

Should be dropped

**Comment by bjarki-andreasen** [comment]
@rlubos

> All cherry-picked commits (those on top of the merge commit) should have the same sauce tag as they had before cherry-picking.

I stored my updated cherry-picked commits using `git patch-format` which for some reason consumed the sauce tags :) Fixed by next force push :)

> not all [nrf noup] seem to have been reapplied after merge, for instance I can't see

Yeah, I updated a previous commit to include changes applied by later commits (effectively squashing them), so they came up as "no change" when cherry picking them, I will treat this as an error going forward instead of just dropping them

> When checking ncs-loot after the merge, I found a couple of problematic [nrf fromlist] commits:

I will add some checks to ensure upstream closed PRs are identified so fromlists can be easily identified and discussed going forward :)

**Comment by bjarki-andreasen** [comment]
@rlubos found a bug in my script, `eac356d34483400ae61b7e743dcbd022e406079a` should now be reverted. I asked @jori-nordic what to do about the other "limbo" commit, waiting to figure out what to do with it (for now treating it as a noup)

**Comment by expired6978** [comment]
Any movement on this? I'm interested in some fixes from the SMF lib that were committed 3 months ago. It seems like there are upstream merge scripts but it looks like they haven't been run in awhile. Is there a cadence/timeline for when upstream merges occur?

**Comment by nordicjm** [comment]
```
b508201e82a [nrf noup] revertme: Resolve merge conflicts
254d002fc81 [nrf noup] revertme: Cover up merge conflicts
```
Are these still needed?

Following noup's are in main but not re-added in here, are they needed?
```
468d06db554 [nrf noup] modules: hal_nordic: need exactly nrf-regtool v5.5.1
8bd088c7c29 [nrf noup] modules: mbedtls: remove deprecated Kconfig
e16bd76f875 [nrf noup] boards: Fix MPC configuration for nRF54L15
c2b79f94fd1 [nrf noup] dts: choose a crypto accelerator for entropy
c62622fb525 [nrf noup] modules: mbedtls: add PSA configurations
339f7a3d661 [nrf noup] drivers: flash: Fix spi_nor_set_address_mode and exit_dpd
f14110a7dfb [nrf noup] modules: mbedtls: Disable configurations in Kconfig.tls-generic
```

**Review by rlubos — APPROVED** [review]

**Review by miha-nordic — APPROVED** [review]

**Review by Vge0rge — APPROVED** [review]

**Review by shanthanordic — APPROVED** [review]
approving from scope and test prespective

**Review by plskeggs — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]
Flash, VFS, Stream Flash looks ok.

**Pull request merged**
