### PR TITLE
Upstream fixes for mesh and mesh friendship

### PR DESCRIPTION
**Pull request by m-alperen-sener**
Mesh fixes
- Stop scanner before resetting mesh
- Invalidate pending entries before calling settings API

Friendship fixes and improvement
- Separate adv tag/set for friend
- Config opt for friend adv latency
- Add extra flag to control seg msg in frnd queue
- Remove illegal use of NET_BUF_FRAG in friend.c"

### CODE REVIEW

**Comment by alxelax** [comment]
Hm, why Bluetooth tests are disabled in CI?

**Comment by m-alperen-sener** [comment]
> Hm, why Bluetooth tests are disabled in CI? These changes especially affect the functionality those tests are responsible to check.

It is a repo access fail, retriggered and it ran.

**Review by alxelax — APPROVED** [review]

**Review by PavelVPV — APPROVED** [review]

**Review by shantha-14 — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
```
d58c813 Revert "[nrf fromtree] bluetooth: mesh: Remove illegal use of NET_BUF_FRAG in friend.c"
```

What happened here? This is not a revert of a fromtree commit. Judging by this commit: https://github.com/zephyrproject-rtos/zephyr/commit/7b4f94220dbd5d65d18a2a5c5272fb9c4432a524

It looks like this should have been

```
[nrf fromtree] Revert "bluetooth: mesh: Remove illegal use of NET_BUF_FRAG in friend.c"
```

That is what I am going to rewrite the title to for NCS v2.3, FYI

**Comment by m-alperen-sener** [comment]
Yeap, my mistake. Thanks for the correction.

**Pull request merged**
