### PR TITLE
Bluetooth: host: GATT Caching fixes

### PR DESCRIPTION
**Pull request by MarekPieta**
Cherry-pick of GATT Caching related fixes to sdk-zephyr.

### CODE REVIEW

**Review by hermabe — APPROVED** [review]

**Comment by MarekPieta** [comment]
If possible, fix for https://github.com/zephyrproject-rtos/zephyr/issues/54770 should be also pulled in (as soon as the issue is fixed in Zephyr upstream)

**Review by alwa-nordic — APPROVED** [review]

**Comment by MarekPieta** [comment]
Added DNM label to avoid merging before we pull in fixes for https://github.com/zephyrproject-rtos/zephyr/issues/54770

**Review by jori-nordic — APPROVED** [review]

**Comment by MarekPieta** [comment]
@miha-nordic, ran BLE nightly tests: https://jenkins-ncs.nordicsemi.no/job/latest/job/night/job/test-fw-nrfconnect-ble_samples/job/master/586/

**Review by miha-nordic — APPROVED** [review]

**Comment by miha-nordic** [comment]
From test point of view this PR is ready to merge. There is no issues on nightly plans related to this changes.

**Review by jori-nordic — APPROVED** [review]

**Comment by MarekPieta** [comment]
Discussed with @pdunaj, decided that the fix is too risky to introduce it after RC1. Removed milestone.

**Pull request merged**
