### PR TITLE
[nrf toup] boards: improve nrf52_pca20020 devicetree

### PR DESCRIPTION
**Pull request by prestegaard**
[nrf toup] boards: improve nrf52_pca20020 devicetree

Signed-off-by: Prestegård <Hakon.Prestegard@nordicsemi.no>

### CODE REVIEW

**Comment by mbolivar** [comment]
@prestegaard it looks like just the name of the pull request was changed, but the commit itself was not changed. Can you please fix it up using `git commit --amend`?

**Comment by prestegaard** [comment]
Hi,
Commit message is now changed to suggested content.

**Comment by nvlsianpu** [comment]
DNM until Upmerge #296 will be merged

**Comment by mbolivar-nordic** [comment]
This PR is very old so I'm going to close it. I think I just got a ping because of the rebase. Please rebase and reopen if still relevant.

**Pull request closed without merging**
