### PR TITLE
test-spec: Reduce for libmodem and iot samples

### PR DESCRIPTION
**Pull request by elisabeth-solheim**
Signed-off-by: Elisabeth Solheim Klakken <elisabeth.solheim@nordicsemi.no>

### CODE REVIEW

**Review by jorgenmk — APPROVED** [review]

**Review by lemrey — APPROVED** [review]
Looks good, @rlubos do you see anything obvious missing?

**Review by rlubos — APPROVED** [review]
Looks fine. I'd like to see a sdk-nrf PR with manifest update though, just to make sure we don't break anything with those changes (CI-wise).

**Comment by rugeGerritsen** [comment]
Thanks! Should the scope of CI-lwm2m-test, CI-modemshell-test, and CI-positioning-test be reduced accordingly as done in https://github.com/nrfconnect/sdk-nrfxlib/pull/699?

**Comment by elisabeth-solheim** [comment]
> Looks fine. I'd like to see a sdk-nrf PR with manifest update though, just to make sure we don't break anything with those changes (CI-wise).
Hi
I have tested it from this PR. https://github.com/nrfconnect/sdk-nrf/pull/7269. Test for the libmodem and iot samples plans are not run in this pr from nrf as expected.

**Pull request merged**
