### PR TITLE
[nrf toup] Do not replace device file for os.devnull

### PR DESCRIPTION
**Pull request by dlu-ch**
Fixes: Replacing /dev/null by regular file on GNU/Linux when executed as root.

### CODE REVIEW

**Review by carlescufi — CHANGES_REQUESTED** [review]
I am sure you didn't want to post a PR with 130 commits.

**Comment by mbolivar-nordic** [comment]
> I am sure you didn't want to post a PR with 130 commits.

That's just because of the rebase I pushed yesterday.

**Comment by mbolivar-nordic** [comment]
This patch should be sent upstream though.

**Review by cvinayak — COMMENTED** [review]
any action here?

**Comment by mbolivar-nordic** [comment]
Please reopen (as a fromlist) if still relevant

**Pull request closed without merging**
