### PR TITLE
[nrf fromlist] drivers: serial: nrfx_uarte: Fix power management

### PR DESCRIPTION
**Pull request by nordic-krch**
Power consumption was still high after putting uarte device into off
state. It was caused by ENDRX interrupt that was triggered after
calling STOPRX. ENDRX event was called with 0 amount but interrupt
got triggered and fifo_read was starting RX again.

Added disabling RX interrupt before disabling UARTE and reenabling at
device activation.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Review by anangl — APPROVED** [review]

**Comment by anangl** [comment]
I think that UARTE driver fixes from https://github.com/zephyrproject-rtos/zephyr/pull/31988 should also be included in NCS 1.5. Maybe those commits could be picked into this PR?

**Comment by nordic-krch** [comment]
@anangl added.

**Review by carlescufi — APPROVED** [review]

**Review by MarekPorwisz — APPROVED** [review]

**Comment by pszkotak** [comment]
@nordic-krch, could you rebase this?
It seems that we need commits bumping up the hal to pass CI tests.

**Comment by carlescufi** [comment]
> @nordic-krch, could you rebase this?
> It seems that we need commits bumping up the hal to pass CI tests.

Tests seem green now, what is the issue?

**Comment by pszkotak** [comment]
> > @nordic-krch, could you rebase this?
> > It seems that we need commits bumping up the hal to pass CI tests.
> 
> Tests seem green now, what is the issue?

PR with the manifest is red on the Zigbee sample build (https://github.com/nrfconnect/sdk-nrf/pull/3853) - https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-3853/5/console.

The https://github.com/nrfconnect/sdk-zephyr/commit/85b46fbe054f6fb35e6a6becaf9b23c18161ef08 should fix it.

**Review by tejlmand — CHANGES_REQUESTED** [review]
Included in #459

**Pull request closed without merging**
