### PR TITLE
[nrf noup] include: net: align RAI socket options

### PR DESCRIPTION
**Pull request by MirkoCovizzi**
This commit aligns some RAI related socket options with modemlib's.

Signed-off-by: Mirko Covizzi <mirko.covizzi@nordicsemi.no>

### CODE REVIEW

**Comment by MirkoCovizzi** [comment]
Values are inverted, also reordered to follow increasing order.

**Comment by rlubos** [comment]
Please open a manifest update PR

**Review by lemrey — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Review by eivindj-nordic — APPROVED** [review]

**Review by carlescufi — CHANGES_REQUESTED** [review]
Is this a candidate for squashing with a previous noup?

**Comment by rlubos** [comment]
> Is this a candidate for squashing with a previous noup?

Good point, this should be squashed with https://github.com/nrfconnect/sdk-zephyr/commit/ef87d64245e68b802fac975fc3ec4d7e7c60b273.

Please add `squash! [nrf noup] include: net: add NCS extensions` below the commit title.

**Comment by MirkoCovizzi** [comment]
> > Is this a candidate for squashing with a previous noup?
> 
> Good point, this should be squashed with [ef87d64](https://github.com/nrfconnect/sdk-zephyr/commit/ef87d64245e68b802fac975fc3ec4d7e7c60b273).
> 
> Please add `squash! [nrf noup] include: net: add NCS extensions` below the commit title.

Like this?

**Comment by rlubos** [comment]
> > > Is this a candidate for squashing with a previous noup?
> > 
> > 
> > Good point, this should be squashed with [ef87d64](https://github.com/nrfconnect/sdk-zephyr/commit/ef87d64245e68b802fac975fc3ec4d7e7c60b273).
> > Please add `squash! [nrf noup] include: net: add NCS extensions` below the commit title.
> 
> Like this?

It seems that you still need an empty line after the title.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
