### PR TITLE
[nrf fromlist] bluetooth: controller: nrf: Provide info about used DPPI resources

### PR DESCRIPTION
**Pull request by anangl**
Upstream PR: zephyrproject-rtos/zephyr#30345

Use common definitions of HAL_USED_PPI_CHANNELS and HAL_USED_PPI_GROUPS
macros that will provide (through z_bt_ctlr_used_nrf_ppi_* variables)
information about either PPI or DPPI (depending on the SoC) resources
used by the Bluetooth controller.
Update also the hal_nordic module revision, to make the related nrfx
allocator aware of those reserved DPPI resources.

### CODE REVIEW

**Comment by grochu** [comment]
Unfortunately, the default configuration (`BT_LL_CHOICE = BT_LL_SOFTDEVICE`) doesn't build as it can't see the `z_bt_ctrl_used_nrf_ppi_channels` symbol. @rugeGerritsen do you have an idea where this symbol is defined in case when SoftDevice Controller is used?

**Comment by rugeGerritsen** [comment]
> Unfortunately, the default configuration (`BT_LL_CHOICE = BT_LL_SOFTDEVICE`) doesn't build as it can't see the `z_bt_ctrl_used_nrf_ppi_channels` symbol. @rugeGerritsen do you have an idea where this symbol is defined in case when SoftDevice Controller is used?

This can be put in `subsys/bluetooth/controller/hci_driver.c`. We use channels 17 - 31: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrfxlib/softdevice_controller/doc/softdevice_controller.html

**Comment by anangl** [comment]
> Unfortunately, the default configuration (`BT_LL_CHOICE = BT_LL_SOFTDEVICE`) doesn't build as it can't see the `z_bt_ctrl_used_nrf_ppi_channels` symbol. @rugeGerritsen do you have an idea where this symbol is defined in case when SoftDevice Controller is used?

@grochu See https://github.com/nrfconnect/sdk-nrf/pull/3444.

**Comment by anangl** [comment]
https://github.com/zephyrproject-rtos/hal_nordic/pull/69 needs to be merged first. Hence the DNM label.

**Comment by grochu** [comment]
> @grochu See [nrfconnect/sdk-nrf#3444](https://github.com/nrfconnect/sdk-nrf/pull/3444).

Thanks, this looks fine. Tested with https://github.com/nrfconnect/sdk-nrf/pull/3444 and Bluetooth samples on nRF53 look good.

**Review by grochu — APPROVED** [review]

**Comment by anangl** [comment]
Updated hal_nordic revision.

**Comment by anangl** [comment]
Merged as part of #402.

**Pull request closed without merging**
