### PR TITLE
[nrf fromtree] boards:arm:nrf9160dk_nrf9160 add support for arduino shields

### PR DESCRIPTION
**Pull request by Embla-Flatlandsmo**
add support for shields that use arduino_i2c and
arduino_serial.

Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/36488

### CODE REVIEW

**Review by ioannisg — CHANGES_REQUESTED** [review]
Must change commit sauce tag to "from tree"

**Comment by carlescufi** [comment]
@Embla-Flatlandsmo is this still necessary? Otherwise please close it.

**Comment by Embla-Flatlandsmo** [comment]
@carlescufi 1: I'm getting the compliance check fail on: UC5 Title exceeds max length (77>75): "[nrf fromlist] boards: arm: nrf9160dk_nrf9160 add support for arduino shields"
How can I change the PR title to make it comply properly? I thought it needed the exact same name as the upstream PR but prepended with the sauce tag.

**Comment by carlescufi** [comment]
This is no longer necessary, the code is already part of the tree.

**Pull request closed without merging**
