### PR TITLE
samples: tfm: Enumerate more test variants

### PR DESCRIPTION
**Pull request by torsteingrindvik**
Some TFM samples run different test suites/cases based on
which configurations are set.
Enumerate more of these to ensure builds are OK,
and allow internal CI to run these on target.

Signed-off-by: Torstein Grindvik <torstein.grindvik@nordicsemi.no>

### CODE REVIEW

**Comment by joerchan** [comment]
@torsteingrindvik Is there anything that is specific to NCS in this commit? From what I can tell this looks fine to be sent upstream.

**Comment by torsteingrindvik** [comment]
> @torsteingrindvik Is there anything that is specific to NCS in this commit? From what I can tell this looks fine to be sent upstream.

Not really.
Will submit to upstream and change to [fromlist]

**Review by magnev — APPROVED** [review]

**Review by frkv — APPROVED** [review]
LGTM

**Review by Vge0rge — APPROVED** [review]
LGTM

**Pull request merged**
