### PR TITLE
[nrf fromtree] net: Add support for DSCP/ECN IPv4/IPv6 header fields

### PR DESCRIPTION
**Pull request by rlubos**

### CODE REVIEW

**Comment by rlubos** [comment]
CC @krish2718

**Review by krish2718 — APPROVED** [review]

**Review by PerMac — APPROVED** [review]

**Comment by PerMac** [comment]
@rlubos  Nrf's Ci exposed a lot of regression with this PR https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9053/4/ Do we need DNM on this PR before integration with nrf issues are resolved?

**Comment by rlubos** [comment]
@PerMac It's nothing, I've messed up conflict resolution when rebasing, should be fixed now.

**Comment by PerMac** [comment]
Clang check required a fix, which was merged recently. Please rebase the PR to get the workflow properly triggered. Sorry for an inconvenience.

**Pull request merged**
