### PR TITLE
v2.4 YOPAN-165 and YOPAN-168

### PR DESCRIPTION
**Pull request by ankuns**
This PR brings in workaround against anomaly 165 and 168 for the nRF5430 SoC.

KRKNWK-19361

### CODE REVIEW

**Review by gmarull — CHANGES_REQUESTED** [review]
Some fromlists should be fromtrees as they’re already merged

**Comment by ankuns** [comment]
> Some fromlists should be fromtrees as they’re already merged

Fixed, there are now `[nrf fromtree]`

**Comment by gmarull** [comment]
> > Some fromlists should be fromtrees as they’re already merged
> 
> Fixed, there are now `[nrf fromtree]`

Some cherry-picks contain two lines for "cherry picked from", should only be one

**Comment by ankuns** [comment]
> Some cherry-picks contain two lines for "cherry picked from", should only be one

fixed

**Review by gmarull — APPROVED** [review]

**Review by martintv — APPROVED** [review]

**Review by mariusz-nordicsemi — APPROVED** [review]

**Pull request merged**
