### PR TITLE
[nrf fromtree] Cherry pick from upstream

### PR DESCRIPTION
**Pull request by piociu**

### CODE REVIEW

**Comment by piociu** [comment]
Just cherry-picking from upstrem. This PR is related to this one: https://github.com/nrfconnect/sdk-mcuboot/pull/111

**Comment by carlescufi** [comment]
You also need to provide a counterpart PR in sdk-nrf to verify that your changes don't break that repo's master.

**Comment by mbolivar-nordic** [comment]
No objections if this is needed now

**Comment by piociu** [comment]
PR in nrf-sdk: https://github.com/nrfconnect/sdk-nrf/pull/2642

**Comment by nvlsianpu** [comment]
@piociu Please fix CI.

**Pull request merged**
