### PR TITLE
[nrf fromtree] samples: boards: nrf: ieee802154: Optimize power on nRF53

### PR DESCRIPTION
**Pull request by pszkotak**
Add an overlay disabling unused peripherals
and UART in the prj.conf.

KRKNWK-8952

https://github.com/zephyrproject-rtos/zephyr/pull/32341

Signed-off-by: Piotr Szkotak <piotr.szkotak@nordicsemi.no>

### CODE REVIEW

**Review by lmaciejonczyk — APPROVED** [review]

**Review by hubertmis — CHANGES_REQUESTED** [review]
I think using [fromlist] here is far-fetched. There are comments in the upsteram PR suggesting that this approach is not correct.

**Comment by pszkotak** [comment]
> I think using [fromlist] here is far-fetched. There are comments in the upsteram PR suggesting that this approach is not correct.

Adding DNM till it's clarified. Will sync these two if there is a need for it.

**Review by MarekPorwisz — APPROVED** [review]

**Comment by tejlmand** [comment]
also remember to point to the upstream PR.

**Review by tejlmand — APPROVED** [review]

**Review by ioannisg — CHANGES_REQUESTED** [review]
pls, change this to from-tree, appropriately.

**Review by shantha-14 — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]

**Pull request merged**
