### PR TITLE
Enable bidirectional LE Audio TWS

### PR DESCRIPTION
**Pull request by erikrobstad**

### CODE REVIEW

**Comment by Thalley** [comment]
This doesn't look correct. 

Ideally you should just cherry-pick 
https://github.com/zephyrproject-rtos/zephyr/commit/249d4774f372bdbbea59c485d4c7d0c1a2a7d336
https://github.com/zephyrproject-rtos/zephyr/commit/c8014d181e55604812edf6956d248f836f99a4dc
https://github.com/zephyrproject-rtos/zephyr/commit/36058480e74703334a933bbfe9b4e496e069a0e9

in that order, but this PR has 5 commits, and the last commit seems like it is missing.

**Comment by erikrobstad** [comment]
> This doesn't look correct.
> 
> Ideally you should just cherry-pick [zephyrproject-rtos/zephyr@249d477](https://github.com/zephyrproject-rtos/zephyr/commit/249d4774f372bdbbea59c485d4c7d0c1a2a7d336) [zephyrproject-rtos/zephyr@c8014d1](https://github.com/zephyrproject-rtos/zephyr/commit/c8014d181e55604812edf6956d248f836f99a4dc) [zephyrproject-rtos/zephyr@3605848](https://github.com/zephyrproject-rtos/zephyr/commit/36058480e74703334a933bbfe9b4e496e069a0e9)
> 
> in that order, but this PR has 5 commits, and the last commit seems like it is missing.

@Thalley
Hmmm, to me it looks like the 3 commits you link to are included, and included in that order?
The two other commits are the remaining commits from the same PR as the last commit you link to. I figured it was cleaner to include all commits from a PR. But this might not be the case?

**Comment by Thalley** [comment]
> Hmmm, to me it looks like the 3 commits you link to are included, and included in that order?
> The two other commits are the remaining commits from the same PR as the last commit you link to. I figured it was cleaner to include all commits from a PR. But this might not be the case?

Yes, my brain read it the opposite direction :D 

No, this looks fine. The changes to the samples and babblesim tests could be excluded, but they shouldn't do any harm :)

**Review by rick1082 — APPROVED** [review]

**Comment by erikrobstad** [comment]
Rebased on newest sdk-zephyr main

**Comment by erikrobstad** [comment]
https://github.com/nrfconnect/sdk-nrf/pull/10138

This PR into sdk-zephyr only affects _Bluetooth LE Audio_.
The CI for the sdk-nrf PR (link) fails for Thread, but this failure has to be caused by something else. The CI for audio passes.

**Pull request merged**
