### PR TITLE
Upmerge branch 2022.12.13

### PR DESCRIPTION
**Pull request by cvinayak**
Merge upstream to commit
https://github.com/zephyrproject-rtos/zephyr/tree/e1e06d05fa8d1b6ac1b0dffb1712e94e308861f8

Pending cherry-pick back:
- [x] d59914d1d1 [nrf noup] ci: clang: parallel execution
- [x] ce6a295246 [nrf noup] ci: NCS-specific CI tweaks
- [x] 39ce36727f [nrf noup] boards: thingy53_nrf5340: Enable MCUboot by default
- [x] 0bff3b69a8 [nrf noup] mgmt/mcumgr: Bootutil hooks to handle image-1
- [x] https://github.com/nrfconnect/sdk-zephyr/pull/1018 action: @krish2718 send PR rebase to the upmerge PR https://github.com/nrfconnect/sdk-zephyr/pull/1012

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by Thalley** [comment]
Just FYI, the LE Audio unicast client is broken until https://github.com/zephyrproject-rtos/zephyr/pull/53074 is merged

**Review by nordicjm — APPROVED** [review]

**Review by edmont — APPROVED** [review]
LGTM (Thread).

**Review by rlubos — APPROVED** [review]

**Review by PavelVPV — APPROVED** [review]

**Review by krish2718 — APPROVED** [review]
For zperf parts

**Review by hubertmis — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]
Tested MCUmgr with smp_svr and MCUboot.  Looks OK.

**Review by alwa-nordic — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
