### PR TITLE
net: coap: Pull various fixes to CoAP client

### PR DESCRIPTION
**Pull request by SeppoTakalo**
Pull fixes from upstream to coap_client used by nRF Cloud libraries.

Internal issue reported: NCSDK-29890

### CODE REVIEW

**Comment by rlubos** [comment]
@carlescufi IMO this qualifies for an exception from the conflict-free cherry-pick rule, fixing dependencies would require to pull this tree-wide change, which does not apply cleanly on it's own:
https://github.com/zephyrproject-rtos/zephyr/commit/c4803752a86
IMO pursuing that further is pointess, let's just ignore the check for this PR.

**Review by juhaylinen — APPROVED** [review]

**Comment by SeppoTakalo** [comment]
Updated the PR.
Now contains only `[nrf fromtree]` as the upstream PR is now merged.

Also fixed some merging issues as I previously had some commits in wrong order. Should apply more cleanly now.

**Comment by SeppoTakalo** [comment]
a bit unfortunate that our CI runs those compliance checks that upsream did not. Now it complains about styling on commits that are already merged in.

**Comment by rlubos** [comment]
> a bit unfortunate that our CI runs those compliance checks that upsream did not. Now it complains about styling on commits that are already merged in.

I guess there's no way around then other than taking this as is.

**Review by rlubos — APPROVED** [review]

**Pull request merged**
