### PR TITLE
[nrf noup] drivers: flash: kconfig: nrf_rram region resolution

### PR DESCRIPTION
**Pull request by michalek-no**
adjusting region resolution to match erase-block-size

### CODE REVIEW

**Comment by michalek-no** [comment]
rebase

**Review by de-nordic — CHANGES_REQUESTED** [review]
There is missing [nrf ...] tag, is there upstream equivalent or this is noup?

**Review by de-nordic — APPROVED** [review]

**Review by sigvartmh — APPROVED** [review]

**Comment by michalek-no** [comment]
rebase

**Review by nvlsianpu — APPROVED** [review]

**Comment by michalek-no** [comment]
rebase

**Pull request merged**
