### PR TITLE
Fix check_compliance.

### PR DESCRIPTION
**Pull request by tejlmand**
Check compliance is failing in sdk-zephyr.

This PR fixes check compliance for Kconfig by defining symbols that exists outside Zephyr.

### CODE REVIEW

**Review by PerMac — APPROVED** [review]

**Review by frkv — APPROVED** [review]
LGTM

**Comment by PerMac** [comment]
do we need a manifest update PR for this one?

**Comment by tejlmand** [comment]
> do we need a manifest update PR in sdk-nrf for this one?

Created one here to run the builds for tfm and crypto:
https://github.com/nrfconnect/sdk-nrf/pull/7011

The changes should not have any impact, but it's always nice to run CI.
We can always decide not to merge the manifest PR, as there is not really a reason in this case.

**Comment by tejlmand** [comment]
The changes in this PR triggers a Kconfig dependency loop when used in NCS.

Need to find a solution that is safe for all use cases.

**Review by carlescufi — CHANGES_REQUESTED** [review]
Can we put all the Kconfig options that we inject here in a new file, `Kconfig.nrf` that we keep in a single patch?

**Comment by mbolivar-nordic** [comment]
stale

**Comment by PerMac** [comment]
Can we keep this open as a reminder, until Torsten is back? This fix is still needed.

**Comment by jfischer-no** [comment]
> Can we keep this open as a reminder, until Torsten is back? This fix is still needed.

Still needed? Can it be closed?

**Pull request closed without merging**
