### PR TITLE
prefer CC310 for zephyr,entropy + Devicetree fixes and documentation

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
The CC310 is the preferred default entropy source on platforms where
it is available. Make it so. This is a noup patch because driver
support is NCS-only.

Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
nrf patch: https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/2261

**Comment by joerchan** [comment]
DNM: Zephyr mergeup in progress, without the mergeup LL_SW_LEGACY would be broken by this PR (removed in upmerge).

**Comment by carlescufi** [comment]
@mbolivar-nordic please merge it once CI is green

**Comment by mbolivar-nordic** [comment]
> @mbolivar-nordic please merge it once CI is green

OK, merging.

**Pull request merged**
