### PR TITLE
nRF54l15DK board support

### PR DESCRIPTION
**Pull request by bjarki-andreasen**
Continuation of #1984 

Identical copy except last commit  is removed

### CODE REVIEW

**Comment by bjarki-andreasen** [comment]
Rebased and re cherry-picked 070b1a4d418729f789e1ed6b4bece7d75496438d

**Review by gmarull — APPROVED** [review]
for reference: 070b1a4d418729f789e1ed6b4bece7d75496438d tuned to skip conflicts with nrf54h20 flpr support (added before these changes upstream)

**Review by carlescufi — APPROVED** [review]

**Comment by bjarki-andreasen** [comment]
Needed commit 6a671ae75e50ff816ffc16fdf29b9b4d46c1b354

**Comment by gchwier** [comment]
some problems with building with MCUboot, try:
`west build $ZEPHYR_BASE/samples/hello_world -p -b nrf54l15dk/nrf54l15/cpuapp -d build-54l-hellomcuboot --sysbuild -- -DSB_CONFIG_BOOTLOADER_MCUBOOT=y`

Looks that not everything was copied to new board, compare files:
 boards/nordic/nrf54l15dk/Kconfig.defconfig boards/nordic/nrf54l15pdk/Kconfig.defconfig

**Comment by bjarki-andreasen** [comment]
Everything upstream was copied downstream (fromtree), there are noups added to the boards downstream to support partition manager and ns variant, see https://github.com/nrfconnect/sdk-zephyr/commits/main/boards/nordic/nrf54l15pdk/Kconfig.defconfig for example :) maybe that's whats missing?

**Comment by gchwier** [comment]
Sysbuild + MCUboot also not working in Upstream, configs for that platform was missing in MCUboot, here is a fix:
https://github.com/mcu-tools/mcuboot/pull/2054

**Pull request merged**
