### PR TITLE
Comparator driver fromtree

### PR DESCRIPTION
**Pull request by bjarki-andreasen**
Import comparator drivers, API and test suites from upstream, including manifest update of hal_nordic with fix for lpcomp

### CODE REVIEW

**Comment by bjarki-andreasen** [comment]
waiting for https://github.com/zephyrproject-rtos/zephyr/pull/79891

**Comment by bjarki-andreasen** [comment]
ping @anangl @nika-nordic @rlubos

**Review by anangl — APPROVED** [review]

**Comment by bjarki-andreasen** [comment]
@carlescufi

**Comment by bjarki-andreasen** [comment]
@hubertmis

**Review by nordic-krch — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Pull request merged**
