### PR TITLE
[nrf noup] action: clang: set the name of checkout repo to zephyr

### PR DESCRIPTION
**Pull request by PerMac**
Fixes isses with downstream forks, where repos names are not zephyr

Will have to be reworked after the upmerge

Signed-off-by: Maciej Perkowski <Maciej.Perkowski@nordicsemi.no>

### CODE REVIEW

**Comment by SebastianBoe** [comment]
I feel that it was a mistake to name the fork sdk-zephyr.

Having the fork's name be zephyr when cloned through west, but sdk-zephyr when cloned directly is unnecessarily confusing.

But I guess that ship has sailed.

**Review by SebastianBoe — APPROVED** [review]

**Comment by PerMac** [comment]
I discuss this action with Anas and probably he won't allow for this change in the upstream.  The problem is this action was defined to use a specific self-hosted AWS agent (not yet in our port) which uses cache and is not wiped clean before running PRs and changing the structure might screw other PR checks.
Anas advice was to change the path in the manifest itself zephyr->sdk-zephyr, which should solve the problem with submanifest import

**Comment by PerMac** [comment]
@mbolivar  I tried a modification which would change the name of the directory, however other errors started popping out. It looks like it messes the original structure and github actions + docker doesn't like this. I think the following steps were trying to use the initial  structure and producing the error, and i guess it would have to be given explicit for all of them any way:
```
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: chdir to cwd ("/__w/sdk-zephyr/sdk-zephyr") set in config.json failed: no such file or directory: unknown
Error: Process completed with exit code 126.
```

Since, according to Marti, this might get a fix with a following west release and would need a post upmerge rework anyway. I would merge this version and see if it helps for the upmerge PR.

**Review by SebastianBoe — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]

**Comment by SebastianBoe** [comment]
We need this to unlock test coverage in the upmerge.

Will be re-worked after/during the upmerge.

**Review by de-nordic — APPROVED** [review]

**Pull request merged**
