### PR TITLE
Configurable Encryption permission for the SMP service and two other small changes

### PR DESCRIPTION
**Pull request by kapi-no**
Cannot be empty

### CODE REVIEW

**Review by de-nordic — APPROVED** [review]

**Comment by kapi-no** [comment]
rebase

**Review by MarekPieta — APPROVED** [review]

**Review by nordicjm — CHANGES_REQUESTED** [review]
0ea81943b30a4ab4e26544f64e594def53d99696 differs from upstream commit 8c0bc54ab09fe84050b4d5a44b1aa4667bcc6cef

**Comment by kapi-no** [comment]
@nordicjm, yes, because it had an entry to migration guide 4.0 that does not exist in the NCS synchronization point. This is [nrf fromtree] commit and will be replaced with the proper change in the next upmerge. Can you remove your NAK?

**Comment by nordicjm** [comment]
> @nordicjm, yes, because it had an entry to migration guide 4.0 that does not exist for the current NCS synchronization point with Zephyr. This is [nrf fromtree] commit and will be replaced with the proper change in the next upmerge. Can you remove your NAK?

Cannot and will not, this is against our rules for fromlist and fromtree, they must be atomic for the upstream PR/commit and apply cleanly, if they do not, they cannot be fromlist or fromtree

**Comment by kapi-no** [comment]
@carlescufi, could you advise us how to move forward?

**Comment by carlescufi** [comment]
> @carlescufi, could you advise us how to move forward?

Let's wait for the upmerge.

**Comment by kapi-no** [comment]
rebase no file diff

**Comment by kapi-no** [comment]
Re-applied cleanly the MCUmgr-related commit since upmerge made it possible

**Pull request merged**
