### PR TITLE
[nrf fromtree] Bluetooth: Controller: Periodic Advertising Synchronization related bugfixes

### PR DESCRIPTION
**Pull request by cvinayak**

### CODE REVIEW

**Comment by cvinayak** [comment]
DNM, waiting for this to be upstream: https://github.com/zephyrproject-rtos/zephyr/pull/42664

**Comment by shantha-14** [comment]
@carlescufi  confirms DNM can be removed

**Comment by mbolivar-nordic** [comment]
> DNM, waiting for this to be upstream: [zephyrproject-rtos/zephyr#42664](https://github.com/zephyrproject-rtos/zephyr/pull/42664)

I cherry-picked this on top after it was merged upstream

**Comment by mbolivar-nordic** [comment]
manifest CI is green on re-run in https://github.com/nrfconnect/sdk-nrf/pull/6859

**Pull request merged**
