### PR TITLE
[nrf fromtree] boards: arm: add nrf9131ek_nrf9131

### PR DESCRIPTION
**Pull request by maxd-nordic**
This patch adds the nRF9131-EK board.

(cherry-picked from 386b65800896262779336e83552c8a44ba96f7a2)

### CODE REVIEW

**Comment by maxd-nordic** [comment]
this is slightly different to the upstream version due to a change in tfm

**Review by carlescufi — APPROVED** [review]

**Review by anangl — CHANGES_REQUESTED** [review]
> this is slightly different to the upstream version due to a change in tfm

As a fromtree commit, it cannot be slightly different. The diff must be the same as in upstream.

**Comment by maxd-nordic** [comment]
> > this is slightly different to the upstream version due to a change in tfm
> 
> As a fromtree commit, it cannot be slightly different. The diff must be the same as in upstream.

How do I fix this? Our version of Zephyr is not up to date enough to support the exact upstream version.

**Comment by anangl** [comment]
> How do I fix this? Our version of Zephyr is not up to date enough to support the exact upstream version.

Cherry-pick more commits from upstream. If that is not feasible, add a temporary `[nrf noup]` commit with the extra changes you need.

**Review by anangl — APPROVED** [review]

**Pull request merged**
