### PR TITLE
Backport: lock the github action runner version to 20.04

### PR DESCRIPTION
**Pull request by thst-nordic**
commit aea5f90d7dcad14695218aae49d37827b416a9cd
    [nrf fromtree] ci: compliance: Use Ubuntu 20.04 runner image
    
    This commit updates the compliance check workflow to use a specific
    runner image version, ubuntu-20.04, instead of the latest version in
    order to prevent any potential breakages due to the 'latest' version
    change by GitHub.
    
commit 7d8541f05e92c4de8e497ccc220794e2d2493e60
    [nrf fromtree] ci: doc: Use Ubuntu 20.04 runner image
    
    This commit updates the documentation build and publish workflows to
    use a specific runner image version, ubuntu-20.04, instead of the
    latest version in order to prevent any potential breakages due to the
    'latest' version change by GitHub.
    
commit 65b0b52715d67967681023651001ace6ac46272c
    [nrf fromtree] ci: coding_guidelines: Use Ubuntu 20.04 runner image
    
    This commit updates the coding guidelines workflow to use a specific
    runner image version, ubuntu-20.04, instead of the latest version in
    order to prevent any potential breakages due to the 'latest' version
    change by GitHub.

### CODE REVIEW

**Comment by thst-nordic** [comment]
This should fix py2.7 issue in 'Run compliance checks on patch series (PR)' action. 
But it will fail on this PR because change isn't incorporated. 
I'll merge without failing CI.

**Review by nordicjm — APPROVED** [review]

**Review by stephanosio — COMMENTED** [review]
You might want to cherry-pick the following commits as well since these workflows are currently failing due to the `latest` image change:

* https://github.com/zephyrproject-rtos/zephyr/commit/1a4105b6b526db5e8dcab59492453cc7f858fb9f
* https://github.com/zephyrproject-rtos/zephyr/commit/18064425236cee67c6fb68617702c5862b945844

**Comment by stephanosio** [comment]
Also not sure what the policy for the "sauce tag" is on the backport branches; the compliance check failure seems to be due to the commit missing `[nrf fromtree]`, not because the change is not merged into the base branch (this workflow triggers on `pull_request`, not `pull_request_target`).

**Comment by thst-nordic** [comment]
I've picked 3 now.  I think backports don't add sauce, but we can check.

**Review by stephanosio — APPROVED** [review]

**Pull request merged**
