### PR TITLE
[nrf fromlist] net: Make net_mgmt queue timeout configurable

### PR DESCRIPTION
**Pull request by krish2718**
This helps us work with low queue depth of network management queue in case the we have high rate events.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/56595 .

Upstream-PR: https://github.com/zephyrproject-rtos/zephyr/pull/57354

### CODE REVIEW

**Review by rlubos — APPROVED** [review]
Looks good but it needs to wait for the upmerge to complete.

**Review by rado17 — APPROVED** [review]

**Comment by krish2718** [comment]
@carlescufi  @gmarull I have fixed the maintainer get issue, but the CI is not checking out the PR, it is doing HEAD.

@stephanosio as per your commit log 37f109a056c9926949d5d87d5319a41bd33f9fe4 this looks expected, but I guess we need to change to below to get this CI pass?

```
diff --git a/.github/workflows/assigner.yml b/.github/workflows/assigner.yml
index 8729315905..58fc1696ee 100644
--- a/.github/workflows/assigner.yml
+++ b/.github/workflows/assigner.yml
@@ -25,6 +25,9 @@ jobs:
 
     - name: Check out source code
       uses: actions/checkout@v3
+      with:
+        ref: ${{ github.event.pull_request.head.sha }}
+        fetch-depth: 0
 
     - name: Run assignment script
       env:
```

**Comment by stephanosio** [comment]
> @stephanosio as per your commit log [37f109a](https://github.com/nrfconnect/sdk-zephyr/commit/37f109a056c9926949d5d87d5319a41bd33f9fe4) this looks expected, but I guess we need to change to below to get this CI pass?

Yes and no. We do not want that change because that will effectively run the assigner script using the `MAINTAINERS.yml` from the PR, which we definitely do not want to do.

This will need to be merged with the "Pull Request Assigner" workflow failing.

**Comment by rlubos** [comment]
I'm confused with 6ee7861c08b0b505577e7f8e7f4afffd0e6b017c:
* Why is it needed specifically for this PR?
* It's referencing non-existing commit title in the fixup line

**Comment by krish2718** [comment]
> I'm confused with [6ee7861](https://github.com/nrfconnect/sdk-zephyr/commit/6ee7861c08b0b505577e7f8e7f4afffd0e6b017c):
> 
> * Why is it needed specifically for this PR?

Not really sure, I thought something to do with upmerge, as the file is deletec I did a `git log --all --full-history -- doc/kconfig.rst` and found that `89babe6a30bb3e5c4fa411168cd4135dbb99e70f` removed this file. It probably triggered now due to some changes in the `assigner` workflow?

> * It's referencing non-existing commit title in the fixup line

See `89babe6a30bb3e5c4fa411168cd4135dbb99e70f`

**Comment by rlubos** [comment]
> > I'm confused with [6ee7861](https://github.com/nrfconnect/sdk-zephyr/commit/6ee7861c08b0b505577e7f8e7f4afffd0e6b017c):
> > 
> > * Why is it needed specifically for this PR?
> 
> Not really sure, I thought something to do with upmerge, as the file is deletec I did a `git log --all --full-history -- doc/kconfig.rst` and found that `89babe6a30bb3e5c4fa411168cd4135dbb99e70f` removed this file. It probably triggered now due to some changes in the `assigner` workflow?
> 
> > * It's referencing non-existing commit title in the fixup line
> 
> See `89babe6a30bb3e5c4fa411168cd4135dbb99e70f`

The commit title is different, so there's no really use for this fixup entry, the tools won't pick it up.

@gmarull Can you review 6ee7861c08b0b505577e7f8e7f4afffd0e6b017c if it's acceptable?

**Comment by krish2718** [comment]
> The commit title is different, so there's no really use for this fixup entry, the tools won't pick it up.

I can match the titles, but I thought as its fixup title doesn't matter as long the fixup line in body matches the original commit, no?

**Review by gmarull — APPROVED** [review]
maintainers noup lgtm

**Comment by rlubos** [comment]
> > > > The commit title is different, so there's no really use for this fixup entry, the tools won't pick it up.
> > > 
> > > 
> > > I can match the titles, but I thought as its fixup title doesn't matter as long the fixup line in body matches the original commit, no?
> > 
> > 
> > I didn't mean to match the commit titles - I meant that the title provided in the fixup line:
> > > fixup! [nrf noup] doc: remove unused kconfig search
> > 
> > 
> > Does not match the title of the original commit it's supposed to be squashed to:
> > > [nrf noup] doc: remove Kconfig search
> 
> Ah, fixed this, I took it from a different commit (on the original branch).
> 
> > It will be tricky for the maintainer to squash it correctly during the rebase if it's not possible to identify the target.

There's still no match (`kconfig` instead of `Kconfig `)

**Comment by krish2718** [comment]
> > > > The commit title is different, so there's no really use for this fixup entry, the tools won't pick it up.
> > > 
> > > 
> > > I can match the titles, but I thought as its fixup title doesn't matter as long the fixup line in body matches the original commit, no?
> > 
> > 
> > I didn't mean to match the commit titles - I meant that the title provided in the fixup line:
> > > fixup! [nrf noup] doc: remove unused kconfig search
> > 
> > 
> > Does not match the title of the original commit it's supposed to be squashed to:
> > > [nrf noup] doc: remove Kconfig search
> 
> Ah, fixed this, I took it from a different commit (on the original branch).
> 
> > It will be tricky for the maintainer to squash it correctly during the rebase if it's not possible to identify the target.

Urgh..sorry, fixed it (copy-pasted).

**Pull request merged**
