### PR TITLE
[nrf fromlist] dts: arm: nordic: Add number of lockable regions and granularity to spu

### PR DESCRIPTION
**Pull request by sigvartmh**
This adds information about the SPU hardware  with the number of
lockable regions and granularity to the SPU node in the device tree.

https://github.com/zephyrproject-rtos/zephyr/pull/23003

### CODE REVIEW

**Comment by nvlsianpu** [comment]
DNM until Upmerge #296 will be merged

**Comment by mbolivar-nordic** [comment]
Could you please rebase?

**Comment by joerchan** [comment]
@sigvartmh This needs to be rebased.

**Comment by sigvartmh** [comment]
Upstream pr is closed. I'll close this one too.

**Pull request closed without merging**
