### PR TITLE
Linker and Llvm toolchain improvements

### PR DESCRIPTION
**Pull request by tejlmand**
List of commits from Zephyr main improving support for LLVM.

### CODE REVIEW

**Review by jukkar — APPROVED** [review]

**Comment by jukkar** [comment]
CI complains now
```
ERROR: Unable to cherry-pick commit 2e3873adde2386e0bc9acdbcdc8d389fdf4b9aee. This means that the upstream commit does not apply cleanly into the NCS fork. This can happen if you modified an upstream commit in order to resolve conflicts, but this is not allowed. Instead, revert any [nrf noup] commits that may be causing the conflict and cherry-pick any additional prior commits from upstream that may be needed in order to avoid a merge conflict. Then you can re-apply the reverted [nrf noup] commits.
```

**Comment by tejlmand** [comment]
> CI complains now

Because upstream contains more commits which alters top-level CMakeLists.txt file, some toolchain infrastructure,  and the upstream manifest, and this causes some of the cherry-picked commits to not apply cleanly.
Feel free to do a manual inspection and ask question if needed:
Examples:
top-level CMakeList.txt and toolchain infrastructure: https://github.com/nrfconnect/sdk-zephyr/pull/2301/commits/28e7eb574dc7a6dc00bcc7c02dbce530e95622b9
Upstream cherry-picked commit: https://github.com/zephyrproject-rtos/zephyr/commit/2e3873adde2386e0bc9acdbcdc8d389fdf4b9aee

picolibc manifest commit in this PR: https://github.com/nrfconnect/sdk-zephyr/pull/2301/commits/168c233995d50f37f5f4c0552ea9a7ca3a46a50b
Upstream cherry-picked commit: https://github.com/zephyrproject-rtos/zephyr/commit/b2eeef4ac9505d8b1d4cfbc51374a96b74064778

This is one of the cases wher a manual override is needed and accepted.
cc @carlescufi

**Comment by jukkar** [comment]
> This is one of the cases wher a manual override is needed and accepted.

Ok, makes sense, just checking.

**Comment by tejlmand** [comment]
closed in favor of #2336

**Pull request closed without merging**
