### PR TITLE
Upmerge 2020 09 16

### PR DESCRIPTION
**Pull request by tejlmand**
sdk-nrf: https://github.com/nrfconnect/sdk-nrf/pull/2918

### CODE REVIEW

**Review by mbolivar-nordic — APPROVED** [review]
Here's the ncs-loot output:

```
$ west ncs-loot zephyr  -z 43102cacfa
=== zephyr (zephyr)
NCS commit (manifest-rev): a649ecaf652cfdf9d2868d4700c5fd2cd344eca4, upstream commit: 43102cacfa77fe0cbaab882c5fe54b5538365d4a
OOT patches: 18 total
- e85c858c21752b50b5b9e6f26cf78300c168a882 [nrf noup] bluetooth: controller: default to SPLIT architecture
- 7b1c9a8c6adc7210d9bf259bbcefefc28a84b130 [nrf noup] doc: Share Kconfig documentation between repos
- d1743ce2c313ae24205f28791edc6aa81b7b2df5 [nrf noup] include: net: add NCS extensions
- ca40a434a9038ea97a12a7955d0ce46c86e0d9cd [nrf noup] net: lib: mqtt: Provide option to enable TLS ession caching
- 32c5d847e8d0196e9b9a32413c67cc98089b1ef2 [nrf noup] dts: add compatibles for CC310 NS access
- d4de842cb11abc3f41364c51805bd5704d656143 [nrf noup] dts: prefer CC310 for zephyr,entropy
- e3ce39771390750b3ddcb51c97db441e0c48f8f0 [nrf fromlist] scripts: kconfig: add dt_alias_enabled
- 88c6be2e7d530ea139b24e2bbc45472b1936769b [nrf fromlist] scripts: edtlib: add EDT.alias2node lookup table
- 7bd90a18c319548415ede8f7a2edc752661aecdb [nrf noup] include: net: add nRF91 extensions
- a6a1fb4642fa9ba5e5dcb5174e127a36a47d9ff6 [nrf noup] include: net: new socket options for NRF91
- 6e10efa3084f85a043c79778ad92b01218cdfe0b [nrf noup] codeowner: Add entry for .github and Jenkinsfile
- a4ef66a2f04c5707def337c7afa7c922d843bc39 [nrf fromlist] Bluetooth: ATT: Fix not restoring buffer state when send fails
- a87b995bec8717597a81e2eb8b68901dbdc889b4 [nrf fromlist] bluetooth: controller: BT_CTLR_CONN_RSSI as a shared controller opt
- 46292e2daf341554b640a14ce8aba5d689eaacd7 [nrf noup] ci: Add Jenkins-based CI for zephyr
- 0639627c37055da25ea3b0a12b04052f83cdac42 [nrf noup] ci: move jenkinsfile to test-ci-nrfconnect-cfg
- 3ea04661ee9a2b888debd360d936349b67e954b2 [nrf noup] tree-wide: support NCS Partition Manager (PM) definitions
- 428909a1bb9129b399d13e046d17b8091fc0aa7e [nrf noup] flash_img: mcuboot: reduce NCS patch
- a649ecaf652cfdf9d2868d4700c5fd2cd344eca4 [nrf temphack] drivers: additional select dependency in clock control
```

When I check out the new upstream merge base (43102cacfa) and cherry pick those on top, I see:

- a4ef66a2f04c5707def337c7afa7c922d843bc39 was merged upstream as 426fb82bd8
- a87b995bec8717597a81e2eb8b68901dbdc889b4 was merged upstream as 69867a48dbe1833730517730c4f76c490ae1a467


These are likely safe to revert downstream before doing the mergeup as well.

After skipping those two cherry-picks, I was able to produce this equivalent tree with linear history:

https://github.com/mbolivar-nordic/fw-nrfconnect-zephyr/tree/upmerge-354-rebase

This tree has no diff with this PR #354 as of commit a649ecaf652cfdf9d2868d4700c5fd2cd344eca4. So this seems fine to me structurally; it's rebasable and we're mostly down to noup patches.

These remaining fromlist patches could be reverted:

- a105ed19af [nrf fromlist] scripts: edtlib: add EDT.alias2node lookup table
- 05c2122bf9 [nrf fromlist] scripts: kconfig: add dt_alias_enabled

The `dt_alias_enabled()` PR was merged upstream in a slightly different shape as 24677f93bcfd71a88cf5f7df9b20fed8cf6f1d6e.

If you handle all that, we will be down to `noup` and `temphack` patches only, which would be nice.

These are minor points, though. No worries if you want to keep this as-is.

**Comment by tejlmand** [comment]
> Here's the ncs-loot output:
> .....

Thanks, I will revert those as well, just to make things neat.

**Review by trond-snekvik — APPROVED** [review]

**Comment by joerchan** [comment]
@tejlmand There are zephyr commits between sections of reverts, what happened there?

**Comment by tejlmand** [comment]
> @tejlmand There are zephyr commits between sections of reverts, what happened there?

Not sure what you mean, this is what I see:
`git log --oneline --graph`
```
* a649ecaf65 (HEAD -> upmerge-branch, tejlmand-ncs/upmerge_2020_09_16) [nrf temphack] drivers: additional select dependency in clock control
* 428909a1bb [nrf noup] flash_img: mcuboot: reduce NCS patch
* 3ea04661ee [nrf noup] tree-wide: support NCS Partition Manager (PM) definitions
* 0639627c37 [nrf noup] ci: move jenkinsfile to test-ci-nrfconnect-cfg
* 46292e2daf [nrf noup] ci: Add Jenkins-based CI for zephyr
*   0d6ddb5739 [nrf mergeup] Merge Zephyr to commit 43102cacfa
|\  
| * 43102cacfa (upstream/master) doc: application: document OVERLAY_CONFIG
| * 85af1bd599 tests: arch: arm: do not build/run test suites for _ns boards
| * ........ Purely upstream commits
| * 7ecc55ac84 Bluetooth: controller: consistent HCI error messages
| * 319be27041 boards: arm: mec15xx: Allow to use some of ADC pins for JTAG tracing
| * 357638955a soc: arm: mchp: Add switch to configure JTAG pins
* | d5b5410951 Revert "[nrf noup] ci: Add Jenkins-based CI for zephyr"
* | 5dfa40724f Revert "[nrf noup] ci: move jenkinsfile to test-ci-nrfconnect-cfg"
* | 74baffe0ad Revert "[nrf noup] tree-wide: support NCS Partition Manager (PM) definitions"
* | c532172dcf Revert "[nrf noup] flash_img: mcuboot: reduce NCS patch"
* | b01087ea5a Revert "[nrf fromtree] lib: fdtable: fix reference counting in z_reserve_fd()"
* | 8598b17f1a Revert "[nrf fromtree] net: sockets: tls: Add helper function to verify protocol"
* | 97cc55b96e Revert "[nrf fromtree] net: sockets: tls: Decouple TLS sockets from net_context"
* | 37f3d8d693 Revert "[nrf fromtree] samples: net: sockets: Increase FD count for TLS echo samples"
* | 9f717792af Revert "[nrf fromtree] net: sockets: tls: Add support for offloaded poll"
* | dd0c2f529b Revert "[nrf fromtree] net: sockets: tls: Add Kconfig option to disable offloaded TLS"
* | 4c3f4155b6 Revert "[nrf fromlist] Bluetooth: Call bt_recv from priority higher that TX thread."
* | 8892b44ecb Revert "[nrf fromtree] lib: openthread: allow passing multiple libraries as mbedtls"
* | 332206bcad (ncs/master) [nrf fromtree] lib: openthread: allow passing multiple libraries as mbedtls

```

**Comment by hakonfam** [comment]
I think you can merge the two commits:
https://github.com/nrfconnect/sdk-zephyr/pull/354/commits/428909a1bb9129b399d13e046d17b8091fc0aa7e
and
https://github.com/nrfconnect/sdk-zephyr/pull/354/commits/3ea04661ee9a2b888debd360d936349b67e954b2

**Comment by utzig** [comment]
I am currently getting:

```
warning: the int symbol SDC_RX_PRIO (defined at /home/utzig/src/Nordic/ncs/nrf/subsys/bluetooth/controller/Kconfig:68) has a non-int default BT_RX_PRIO_HIGH (undefined)
warning: undefined symbol BT_RX_PRIO_HIGH:

- Referenced at /home/utzig/src/Nordic/ncs/nrf/subsys/bluetooth/controller/Kconfig:68:

config SDC_RX_PRIO
	int
	default BT_RX_PRIO_HIGH
	depends on BT_LL_SOFTDEVICE && BT
```

**Comment by tejlmand** [comment]
> I am currently getting:
> 

you are probably trying this PR directly on nrf/master, which won't work.
That why there is also a nrf upmerge PR.

**Comment by utzig** [comment]
> > I am currently getting:
> 
> you are probably trying this PR directly on nrf/master, which won't work.
> That why there is also a nrf upmerge PR.

duh, thanks, I was not aware, I will cherry-pick from there! ;-)

Is there some documentation explaining how the upmerge process is done?

**Comment by tejlmand** [comment]
>     * [a4ef66a](https://github.com/nrfconnect/sdk-zephyr/commit/a4ef66a2f04c5707def337c7afa7c922d843bc39) was merged upstream as [426fb82](https://github.com/nrfconnect/sdk-zephyr/commit/426fb82bd861a99e7b3c5c8ae075a0c3c5145ad1)
> 
>     * [a87b995](https://github.com/nrfconnect/sdk-zephyr/commit/a87b995bec8717597a81e2eb8b68901dbdc889b4) was merged upstream as [69867a4](https://github.com/nrfconnect/sdk-zephyr/commit/69867a48dbe1833730517730c4f76c490ae1a467)
> 
> 
> These are likely safe to revert downstream before doing the mergeup as well.

@mbolivar-nordic  Done.


> These remaining fromlist patches could be reverted:
> 
>     * [a105ed1](https://github.com/nrfconnect/sdk-zephyr/commit/a105ed19afa5ae73d876a983bb13bf163c9f2c72) [nrf fromlist] scripts: edtlib: add EDT.alias2node lookup table
> 
>     * [05c2122](https://github.com/nrfconnect/sdk-zephyr/commit/05c2122bf979b6ed20cdc3302084cb464d2bda9e) [nrf fromlist] scripts: kconfig: add dt_alias_enabled

Those commits are further back in history.
Shouldn't they have been reverted at an earlier upmerge ?
Will reverting them now not create more noise ?

> I think you can merge the two commits:
> [428909a](https://github.com/nrfconnect/sdk-zephyr/commit/428909a1bb9129b399d13e046d17b8091fc0aa7e)
> and
> [3ea0466](https://github.com/nrfconnect/sdk-zephyr/commit/3ea04661ee9a2b888debd360d936349b67e954b2)

@hakonfam  Done

**Comment by tejlmand** [comment]
Updated to Zephyr-v2.4.0
https://github.com/zephyrproject-rtos/zephyr/releases/tag/zephyr-v2.4.0

**Comment by mbolivar-nordic** [comment]
> Those commits are further back in history.
> Shouldn't they have been reverted at an earlier upmerge ?
> Will reverting them now not create more noise ?

Yep, if they're already brought in via upmerge, there's nothing else we can do until rebase.

**Comment by nordic-krch** [comment]
@tejlmand can you cherry-pick:
- https://github.com/nrfconnect/sdk-zephyr/pull/351/commits/9183c025238c0158ff035eb40e454647f5ad5dd7
- https://github.com/nrfconnect/sdk-zephyr/pull/351/commits/2031389c8d1ff5bd409e2fda7bfc0552a7d8a2aa

also once those are picked you can delete:
- https://github.com/nrfconnect/sdk-zephyr/pull/354/commits/20f3099f4081dbd919da60957ba14f9fe24c2121

**Review by rlubos — APPROVED** [review]

**Comment by tejlmand** [comment]
> @tejlmand can you cherry-pick:
> ...
> also once those are picked you can delete:

Done

**Review by joerchan — APPROVED** [review]

**Pull request merged**
