### PR TITLE
[nrf fromlist] samples: tfm: Add PSA Protected Storage sample

### PR DESCRIPTION
**Pull request by andvib**
Add sample showing PSA Protected Storage API usage

Upstream Zephyr PR: https://github.com/zephyrproject-rtos/zephyr/pull/35226

Signed-off-by: Andreas Vibeto <andreas.vibeto@nordicsemi.no>

sdk-nrf manifest PR: https://github.com/nrfconnect/sdk-nrf/pull/4684

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]
+1, assuming this is cherry-picked from the already-approved upstream PR

**Comment by ioannisg** [comment]
@andvib can you link a PR for manifest-update in SDK nrf?

**Review by oyvindronningstad — APPROVED** [review]

**Comment by andvib** [comment]
> @andvib can you link a PR for manifest-update in SDK nrf?

Didn't think about that - thanks! (Added link in description)

**Comment by ioannisg** [comment]
@carlescufi @tejlmand pls take a look at this cherry-pick from upstream. This PR (unfortunately) did not make it for the v2.6-RC1 cut, but it was reviewed, anyways.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
