### PR TITLE
[nrf fromlist] drivers: mspi: Add driver for Designware SSI based controllers

### PR DESCRIPTION
**Pull request by anangl**
Add a generic driver for controllers based on the Designware SSI core.
With small vendor-specific adaptations covering integration details,
it should be possible to use it for many devices.

### CODE REVIEW

**Comment by anangl** [comment]
Rebased.

**Comment by anangl** [comment]
Rebased.

**Review by nordic-piks — APPROVED** [review]
Test execution at CI OK, newly added tests executed and passed.

**Review by nordic-segl — APPROVED** [review]

**Review by shanthanordic — APPROVED** [review]
approiving for scope

**Review by de-nordic — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]

**Pull request merged**
