### PR TITLE
nRF54L15 FLPR misc test fixes

### PR DESCRIPTION
**Pull request by masz-nordic**

### CODE REVIEW

**Review by jaz1-nordic — APPROVED** [review]

**Review by nika-nordic — APPROVED** [review]

**Comment by anangl** [comment]
All these commits are merged upstream, so it would be better to cherry pick them as `[nrf fromtree]`.

**Comment by masz-nordic** [comment]
@anangl done

**Comment by anangl** [comment]
> @anangl done

`[nrf fromtree]` commits should refer to SHAs of the merged commits, not those from PRs, so you need to use:
- [e17b3fd884c8090ae2a1e56d4c999103800254da](https://github.com/zephyrproject-rtos/zephyr/commit/e17b3fd884c8090ae2a1e56d4c999103800254da)
- [68c48cd1168e409cb64170f6fb5c7925e1e935f8](https://github.com/zephyrproject-rtos/zephyr/commit/68c48cd1168e409cb64170f6fb5c7925e1e935f8)
- [8999446ab81a479fd74d6dab329a65c653c47f3c](https://github.com/zephyrproject-rtos/zephyr/commit/8999446ab81a479fd74d6dab329a65c653c47f3c)
- [809c6c34d376d8dd91822f5cda93bc5f23c52fdc](https://github.com/zephyrproject-rtos/zephyr/commit/809c6c34d376d8dd91822f5cda93bc5f23c52fdc)

**Comment by masz-nordic** [comment]
@anangl My bad, fixed.

**Review by anangl — APPROVED** [review]

**Pull request merged**
