### PR TITLE
NAT64 implementation 

### PR DESCRIPTION
**Pull request by MarGasiorek**
This PR implements modules which allow to use NAT64 from OT stack.

### CODE REVIEW

**Comment by rlubos** [comment]
If we're going public with this, why not send the patch upstream? I'm really not in favor of maintaining such a large noup patches.

**Comment by jukkar** [comment]
I agree with @rlubos, this code is quite generic and the Nordic specific "secret sauce" is not really there, it would make sense to upstream this.

**Comment by MarGasiorek** [comment]
PR in zephyr created: https://github.com/zephyrproject-rtos/zephyr/pull/75012

**Comment by rlubos** [comment]
Thanks for opening upstream PR, commits should be marked with `[nrf fromlist]` now (or `[nrf fromtree]` if we can wait for the upstream PR to be merged).

**Comment by MarGasiorek** [comment]
Tracked in separate PR.

**Pull request closed without merging**
