### PR TITLE
mcumgr: img_mgmt: Fix using direct-xip mode in the NCS and friends

### PR DESCRIPTION
**Pull request by MarekPieta**
Fix check for chosen code partition in direct-xip mode and improve image version comparison.

### CODE REVIEW

**Review by de-nordic — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Comment by MarekPieta** [comment]
Fixed build issues related to the potentially undefined `PM_MCUBOOT_SECONDARY_PAD_SIZE`.
Also updated commits from `fromlist` to `fromtree` as my PRs are already merged upstream.

**Review by de-nordic — APPROVED** [review]

**Comment by MarekPieta** [comment]
@de-nordic, I had to add a few more fixes. Please rereview the last commit

**Comment by MarekPieta** [comment]
@de-nordic, I did not modify it at all. Should we report this on NCS CI channel ?

**Comment by nordicjm** [comment]
This issue is known already by @gmarull and can be ignored

**Review by nordicjm — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Pull request merged**
