### PR TITLE
[nrf noup] include: net: add nRF91 extensions

### PR DESCRIPTION
**Pull request by tommi-m**
Add some socket options to Zephyr header, which will be useful
for nRF91.

-SO_SNDTIMEO
-MSG_TRUNC

Signed-off-by: Tommi Mammela <tommi.mammela@nordicsemi.no>

### CODE REVIEW

**Comment by nvlsianpu** [comment]
DNM until Upmerge #296 will be merged

**Comment by lemrey** [comment]
Why `[nrf noup]`, couldn't we send these upstream?

**Comment by rlubos** [comment]
@lemrey I don't think bare symbols w/o implementation would be accepted.

**Comment by rlubos** [comment]
Please rebase, I won't be able to merge with failing CI.

**Pull request merged**
