### PR TITLE
DTLS Connection ID Support

### PR DESCRIPTION
**Pull request by plskeggs**
This updates commits from https://github.com/zephyrproject-rtos/zephyr/pull/36738, and builds on them.
This is a downstream version of my upstream PR https://github.com/zephyrproject-rtos/zephyr/pull/44914

- point to PR for mbed TLS also for CID: https://github.com/zephyrproject-rtos/mbedtls/pull/36
- complete the existing support for user-provided cipherlist so it functions
- improve debug logging
- add extended master secret control
- enable server name indication for DTLS even if x509 certs not enabled
- add function to query the peer's CID

### CODE REVIEW

**Review by mbolivar-nordic — APPROVED** [review]
No objections as long as you really need this now and cannot wait for the next upmerge.

**Comment by jfischer-no** [comment]
Looks like a draft, convert to draft.

**Comment by plskeggs** [comment]
Upstream PR merged today https://github.com/zephyrproject-rtos/zephyr/pull/61483.

Should be in sdk-zephyr with the next upmerge.

**Comment by beriberikix** [comment]
@plskeggs do you know when the next upmerged is planned? Thanks!

**Comment by de-nordic** [comment]
> @plskeggs do you know when the next upmerged is planned? Thanks!

It is already part of next upmerge here: https://github.com/nrfconnect/sdk-nrf/pull/12112, the upmerge is going through tests now.

**Pull request closed without merging**
