### PR TITLE
[nrf fromlist] scripts: zephyr modules: introducing Zephyr module dep…

### PR DESCRIPTION
**Pull request by tejlmand**
…endency handling

This commit introduces the possibility of adding dependencies between
Zephyr modules to ensure that a Zephyr module on which other modules
depends is processed first.

The dependency chain is ordered using a topological sort.

This allows to add dependencies to a zephyr/module.yml as:

build:
  cmake: .
  depends:
    - fatfs

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
No objections -- I'm guessing you want this in before the next mergeup?

**Comment by mbolivar-nordic** [comment]
(I'm assuming you can't wait for the upstream commit to go in after zephyr v2.3 and brought into NCS in the usual way)

**Comment by tejlmand** [comment]
> No objections -- I'm guessing you want this in before the next mergeup?
> (I'm assuming you can't wait for the upstream commit to go in after zephyr v2.3 and brought into NCS in the usual way)

I leave that for @tomchy to answer, cause he will be the one following up for the Zigbee library, to make it even nicer shaped.
I just wanted to get everything in place, for him to continue when he's ready.

**Comment by tomchy** [comment]
Hi,
It would be great if we can get this in before the next (Q3/Q4) NCS release. I consider it as a technical dept, so we do not expect it to be fixed in the upcoming release, but if we leave it for a couple of months, we will simply forget about it and never fix it :slightly_smiling_face:

**Comment by mbolivar-nordic** [comment]
> It would be great if we can get this in before the next (Q3/Q4) NCS release. I consider it as a technical dept, so we do not expect it to be fixed in the upcoming release, but if we leave it for a couple of months, we will simply forget about it and never fix it slightly_smiling_face

This needs to be rebased and it would require approval from @shantha-14 to be merged at this point.

**Comment by tomchy** [comment]
What is the reason to merge it now?
I'm not requesting to merge this ASAP, but this year.

**Comment by tomchy** [comment]
It looks as if this feature made its way to the Zephyr's upstream (https://github.com/zephyrproject-rtos/zephyr/commit/3917ee51a9c971bd75742e968a4efb09a9e90e17) :tada:

**Comment by tejlmand** [comment]
closed, will be included in an mergeup.

**Pull request closed without merging**
