### PR TITLE
Listen interval ps

### PR DESCRIPTION
**Pull request by ajayparida**

### CODE REVIEW

**Comment by ajayparida** [comment]
@sachinthegreen @krish2718 @rado17

**Review by sachinthegreen — APPROVED** [review]

**Review by rado17 — APPROVED** [review]

**Review by udaynordic — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Comment by rlubos** [comment]
I'm not really sure what's with the `CI/Jenkins/ZEPHYR ` job here, I'll try to rerun manually.

**Comment by rlubos** [comment]
@ajayparida There's a conflict now

**Comment by awojasinski-nordicsemi** [comment]
Looks like alignment in sdk-nrf is needed I have multiple compilation errors related to unaligned wifi driver in NCS
https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11057/10/testReport/junit/nrf5340dk_nrf5340_cpuapp_wifi_shell_sample.nrf7001_eks_cpunet/shell/Build___Test_with_Twister___Twister_1_10___wifi_shell_sample_nrf7001_eks_cpunet_shell/

```
In file included from ../../../../../nrf/drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c:29:
../../../../../nrf/drivers/wifi/nrf700x/zephyr/inc/zephyr_wifi_mgmt.h:39:41: error: 'struct wifi_ps_mode_params' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
   39 |                                  struct wifi_ps_mode_params *ps_mode_params);
      |                                         ^~~~~~~~~~~~~~~~~~~
../../../../../nrf/drivers/wifi/nrf700x/zephyr/inc/zephyr_wifi_mgmt.h:64:44: error: 'struct wifi_ps_timeout_params' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
   64 |                                     struct wifi_ps_timeout_params *ps_timeout);
      |                                            ^~~~~~~~~~~~~~~~~~~~~~
../../../../../nrf/drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c:492:10: error: 'const struct net_wifi_mgmt_offload' has no member named 'set_power_save_mode'; did you mean 'set_power_save'?
  492 |         .set_power_save_mode = wifi_nrf_set_power_save_mode,
      |          ^~~~~~~~~~~~~~~~~~~
      |          set_power_save
../../../../../nrf/drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c:492:32: error: initialization of 'int (*)(const struct device *, struct wifi_ps_config *)' from incompatible pointer type 'int (*)(const struct device *, struct wifi_ps_mode_params *)' [-Werror=incompatible-pointer-types]
  492 |         .set_power_save_mode = wifi_nrf_set_power_save_mode,
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../nrf/drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c:492:32: note: (near initialization for 'wifi_offload_ops.get_power_save_config')
../../../../../nrf/drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c:495:10: error: 'const struct net_wifi_mgmt_offload' has no member named 'set_power_save_timeout'; did you mean 'set_power_save'?
  495 |         .set_power_save_timeout = wifi_nrf_set_power_save_timeout,
      |          ^~~~~~~~~~~~~~~~~~~~~~
      |          set_power_save
../../../../../nrf/drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c:495:35: error: initialization of 'int (*)(const struct device *, struct wifi_reg_domain *)' from incompatible pointer type 'int (*)(const struct device *, struct wifi_ps_timeout_params *)' [-Werror=incompatible-pointer-types]
  495 |         .set_power_save_timeout = wifi_nrf_set_power_save_timeout,
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../nrf/drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c:495:35: note: (near initialization for 'wifi_offload_ops.reg_domain')
```

**Pull request merged**
