### PR TITLE
Update adc driver to support nRF54L15

### PR DESCRIPTION
**Pull request by kl-cruz**
Changes cherry picked from: https://github.com/zephyrproject-rtos/zephyr/pull/68692

### CODE REVIEW

**Review by gmarull — CHANGES_REQUESTED** [review]
patches should all be `fromlist`

**Review by nordic-segl — APPROVED** [review]

**Comment by rlubos** [comment]
@kl-cruz Please open a manifest PR in `sdk-nrf`.

**Review by nordicjm — CHANGES_REQUESTED** [review]
Does not match upstream PR

**Comment by nordicjm** [comment]
CC @gmarull

**Comment by kl-cruz** [comment]
> @kl-cruz Please open a manifest PR in `sdk-nrf`.

@rlubos done: https://github.com/nrfconnect/sdk-nrf/pull/14955

**Review by miha-nordic — APPROVED** [review]

**Comment by kl-cruz** [comment]
> Does not match upstream PR

I added right information

**Comment by nordicjm** [comment]
> > Does not match upstream PR
> 
> I added right information

Where? There's 4 commits in upstream and there's 3 commits here, this issue is still not addressed

**Comment by kl-cruz** [comment]
> > > Does not match upstream PR
> > 
> > 
> > I added right information
> 
> Where? There's 4 commits in upstream and there's 3 commits here, this issue is still not addressed

Ok, I see.

**Comment by kl-cruz** [comment]
@nordicjm Done

**Review by nordicjm — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Pull request merged**
