### PR TITLE
[nrf noup] subsys: storage: Remove custom flash_map_default.c

### PR DESCRIPTION
**Pull request by osaether**
Remove custom flash_map_defult.c for Partition Manager.

Ref: NCSDK-5469

Signed-off-by: Ole Sæther <ole.saether@nordicsemi.no>

### CODE REVIEW

**Comment by hakonfam** [comment]
Note that this commit removes one of the patches introduced in https://github.com/nrfconnect/sdk-zephyr/commit/399915c9530b7ec9d65583a657f40c02ea571c3b#diff-21c5ca53453de2a3442e257c979a64d3b33975d8427bfdc5d88ed13bbe97855aR13 
so it should be squashed on next upmerge.

I'm not sure how to correctly communicate that.

**Comment by nvlsianpu** [comment]
^^ what commit should be squashed to which on? We have list we are using to menage things like that.

**Comment by hakonfam** [comment]
This is part of the treewide partition manager changes commit. It is linked above.

**Review by nvlsianpu — APPROVED** [review]
@hakonfam I will update the upmerge schedule accordingly for having info you mentioned.

**Review by mbolivar-nordic — APPROVED** [review]
Looks good, but where's the sdk-nrf PR so we can check CI before merging?

**Comment by mbolivar-nordic** [comment]
NVM, I missed the bot comment.

**Pull request merged**
