### PR TITLE
Tfm sample.yaml fixes

### PR DESCRIPTION
**Pull request by oyvindronningstad**
Mirror of https://github.com/zephyrproject-rtos/zephyr/pull/31931 (Merged)

### CODE REVIEW

**Review by andvib — APPROVED** [review]

**Comment by oyvindronningstad** [comment]
@shantha-14 @andvib Note that this PR can be merged if we want to fix the TFM on-target twister CI for 1.5.

**Review by ioannisg — APPROVED** [review]

**Comment by ioannisg** [comment]
@oyvindronningstad have we merged the upstream PRs already?

**Comment by ioannisg** [comment]
Ah, right, saw that now. Maybe add the original commit SHAs in the commit messages?

**Comment by ioannisg** [comment]
I think this is almost no risk, we can merge that.

**Comment by oyvindronningstad** [comment]
>Ah, right, saw that now. Maybe add the original commit SHAs in the commit messages?

It would mean rerunning CI. Should I add the SHA?

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
