### PR TITLE
hal_nordic: integrate nrf_802154 component into hal_nordic

### PR DESCRIPTION
**Pull request by e-rk**
This PR provides new integration scheme for nRF IEEE 802.15.4 radio driver.

Upstream PR: zephyrproject-rtos/zephyr#33500

Signed-off-by: Rafał Kuźnia <rafal.kuznia@nordicsemi.no>

### CODE REVIEW

**Comment by e-rk** [comment]
I am unable to remove people unrelated to this PR from reviewers. If you are not @carlescufi or @tejlmand then please disregard this PR.

**Comment by nvlsianpu** [comment]
@e-rk rebase?

**Comment by e-rk** [comment]
@nvlsianpu I will rebase once https://github.com/nrfconnect/sdk-zephyr/pull/479 is merged. I depend on some content from that PR.

**Comment by e-rk** [comment]
Rebased on latest master.

**Review by tejlmand — CHANGES_REQUESTED** [review]
Blocked due to this https://github.com/nrfconnect/sdk-nrf/pull/4146#pullrequestreview-624653922

**Review by tejlmand — APPROVED** [review]
looks great

**Comment by e-rk** [comment]
Converted commits to fromtree, since https://github.com/zephyrproject-rtos/zephyr/pull/33500 was merged.

**Review by czeslawmakarski — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
