### PR TITLE
[nrf noup] boards: nordic: Turn on NRFS globally

### PR DESCRIPTION
**Pull request by zycz**
Turn on NRFS globaly so turning off
suspending MRAM for NRF54H20 DK will work.

### CODE REVIEW

**Review by tomchy — APPROVED** [review]

**Review by pdunaj — APPROVED** [review]

**Comment by zycz** [comment]
Need to disable NRFS when MISRA_SANE is on - IPC uses variable length array -which is unacceptable with MISRA_SANE on.

**Comment by anangl** [comment]
Please add `nrf-squash! [nrf noup] boards: nordic: Turn off MRAM suspend for NRF54H20 DK` at the top of the commit message.

**Comment by zycz** [comment]
> Please add `nrf-squash! [nrf noup] boards: nordic: Turn off MRAM suspend for NRF54H20 DK` at the top of the commit message.

done

**Comment by anangl** [comment]
> > Please add `nrf-squash! [nrf noup] boards: nordic: Turn off MRAM suspend for NRF54H20 DK` at the top of the commit message.
> 
> done

Sorry for being a bit imprecise. This line should be the first one in the body of the commit message, not its title.

**Review by shanthanordic — APPROVED** [review]
approving as the soln was agreed. sdk-nrf PR was approved by stakeholders

**Review by anangl — APPROVED** [review]

**Pull request merged**
