### PR TITLE
[nrf fromtree] boards: nordic: ipc node added dcache alignement

### PR DESCRIPTION
**Pull request by lstnl**
dcache-alignement needs to be defined for ipc to have consistent memory organization on both endpoints, when shared memory is cacheable. nrf54h20 and nrf9280 are using cacheable shared memory.
This is applied for ipc with icmsg backend.

Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/79389

This is needed for 2.8.0
This change will work with new secdom sysctrl bundle.

sdk-nrf PR
https://github.com/nrfconnect/sdk-nrf/pull/17644

### CODE REVIEW

**Review by 57300 — APPROVED** [review]

**Review by anhmolt — APPROVED** [review]

**Review by masz-nordic — APPROVED** [review]

**Review by jaz1-nordic — APPROVED** [review]

**Comment by tmon-nordic** [comment]
This should be changed from nrf fromlist to nrf fromtree because it is merged upstream.

**Comment by lstnl** [comment]
> This should be changed from nrf fromlist to nrf fromtree because it is merged upstream.

Changed

**Comment by lstnl** [comment]
This is breaking change and not compatible with old secdom sysctrl bundles. This can be merged when new bundle (probably (7.0.0) will be released.

**Comment by anhmolt** [comment]
This was merged as part of PR https://github.com/nrfconnect/sdk-zephyr/pull/2153. Closing this.

**Pull request closed without merging**
