### PR TITLE
ci: Update test-spec.yml with adding FEM to CI

### PR DESCRIPTION
**Pull request by dawidprzybylo**
Extend sdk-zephyr CI with FEM test label.

### CODE REVIEW

**Review by jciupis — APPROVED** [review]

**Comment by jciupis** [comment]
@dawidprzybylo due to an ongoing upmerge, this PR is going to be blocked until the upmerge ends. Maybe it would be a better idea to retarget the PR to the upmerge branch and make use of the change while testing the upmerge? Please synchronize with @rlubos on that.

**Comment by dawidprzybylo** [comment]
> @dawidprzybylo due to an ongoing upmerge, this PR is going to be blocked until the upmerge ends. Maybe it would be a better idea to retarget the PR to the upmerge branch and make use of the change while testing the upmerge? Please synchronize with @rlubos on that.

test-specs.yml is NRF specific, it is not present in upmerge branch: 
https://github.com/zephyrproject-rtos/zephyr/tree/main/.github

**Review by rlubos — APPROVED** [review]

**Comment by rlubos** [comment]
You can open a PR against upmerge branch if you want. Otherwise I'd prefer to wait till the upmerge ends, not to "rebase" the upmerge PR yet another time.

**Comment by dawidprzybylo** [comment]
> You can open a PR against upmerge branch if you want. Otherwise I'd prefer to wait till the upmerge ends, not to "rebase" the upmerge PR yet another time.

Crated PR: https://github.com/rlubos/sdk-zephyr/pull/4

**Pull request closed without merging**
