### PR TITLE
[nrf fromlist] nRF SoCs: Power consumption related fixes

### PR DESCRIPTION
**Pull request by anangl**
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/29409

### CODE REVIEW

**Comment by anangl** [comment]
https://github.com/zephyrproject-rtos/hal_nordic/pull/62 needs to be merged first.

**Review by pdunaj — APPROVED** [review]

**Comment by pdunaj** [comment]
Hi @anangl , what is wrong with CI? The change is simple and should just pass. Can you resubmit?

**Comment by anangl** [comment]
> Hi @anangl , what is wrong with CI? The change is simple and should just pass. Can you resubmit?

Compliance check fails because of the gitlint issues listed above - both commit titles became too long after expanding them with the `[nrf fromlist]` tag. But I cannot shorten them, the original titles need to be preserved.

**Comment by tejlmand** [comment]
> But I cannot shorten them, the original titles need to be preserved.

Is that required ?
I usually just shorten them, but ensuring they are easily identified on next upmerge.

The `[nrf fromlist]` commit will be reverted with the upmerge where same commit is introduced upstream.

**Comment by anangl** [comment]
> > But I cannot shorten them, the original titles need to be preserved.
> 
> Is that required ?
> I usually just shorten them, but ensuring they are easily identified on next upmerge.

I thought the original titles must stay untouched, as they are used for identification of the commits during the upmerge, but apparently I was wrong, and only part of them is sufficient for this. I already wrapped those titles as I saw it was done in some other PR.

**Comment by tejlmand** [comment]
> I thought the original titles must stay untouched, as they are used for identification of the commits during the upmerge

They are used, so keeping them identical, or as close as possible, is nice.
But still, it's a `[fromlist]` so someone could request a different message in the title :wink: upstream.
Or even a completely different implementation.

**Comment by pdunaj** [comment]
Hi @carlescufi , @anangl , it's green :)

**Comment by pdunaj** [comment]
ping

**Comment by pdunaj** [comment]
@carlescufi @anangl Can it go in?

**Comment by carlescufi** [comment]
> @carlescufi @anangl Can it go in?

It will go in

**Comment by tejlmand** [comment]
covered in #384

**Comment by carlescufi** [comment]
Replaced by https://github.com/nrfconnect/sdk-zephyr/pull/384

**Pull request closed without merging**
