### PR TITLE
[nrf fromtree] manifest: hal_nordic: Pull nRF Wi-Fi removal

### PR DESCRIPTION
**Pull request by krish2718**
Pulls PR that removed nRF Wi-Fi.

Signed-off-by: Chaitanya Tata <Chaitanya.Tata@nordicsemi.no>
(cherry picked from commit e512151474ca964302de2e9f8d25ecf13e3bcb16)

### CODE REVIEW

**Review by bama-nordic — APPROVED** [review]

**Review by sachinthegreen — APPROVED** [review]

**Comment by shanthanordic** [comment]
removed milestone

**Comment by shanthanordic** [comment]
why is there an empty file ?

**Comment by krish2718** [comment]
> why is there an empty file ?

Oops, forgot to pull in the fix for this from upstream, it's fixed now, thanks.

**Review by adigie — APPROVED** [review]

**Comment by krish2718** [comment]
Part of https://github.com/nrfconnect/sdk-zephyr/pull/2300

**Pull request closed without merging**
