### PR TITLE
[nrf fromtree] Direction Finding connected mode feature and other fixes

### PR DESCRIPTION
**Pull request by ppryga**
Adds missing parts of direction finding connected mode.
Adds fixes for issues related with direction finding an new implementation of LLPCs.

### CODE REVIEW

**Comment by ppryga** [comment]
Changed west.yml to fetch changes in sdk-zephyr PR: https://github.com/nrfconnect/sdk-zephyr/pull/724 that are required to build code in this PR.

**Comment by ppryga** [comment]
The PR is referenced in this nRF SDK PR: https://github.com/nrfconnect/sdk-nrf/pull/6744.

**Review by kruithofa — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]

**Comment by ppryga** [comment]
Added four more commits that solve problem with deceives disconnection.

**Comment by mbolivar-nordic** [comment]
@ppryga please fix the compliance failures. Note that commit d992b503bbef619b5747397fb7193faf49865792 extends the commit message length, so there is no need to truncate the shortlogs.

For example,

```
[nrf fromtree] Bluetooth: controller: fixing up problem in ...
... collision handling
```

should be

```
[nrf fromtree] Bluetooth: controller: fixing up problem in collision handling
```

instead

**Comment by ppryga** [comment]
The CI verifying this PR is green: https://github.com/nrfconnect/sdk-nrf/pull/6744. The PR may be merged.

**Comment by ppryga** [comment]
Fixed compliance issues related with commit title line.
No changes in code.

**Pull request merged**
