### PR TITLE
[nrf fromtree] net: openthread: Requirements for samples alignment and features support

### PR DESCRIPTION
**Pull request by edmont**
Cherry-pick dependencies for https://github.com/nrfconnect/sdk-nrf/pull/2707

Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>

### CODE REVIEW

**Comment by rlubos** [comment]
DNM for now, we can't merge `west.yml` referencing a PR.

**Comment by rlubos** [comment]
It seems that cherry-picked commits also needs your signoff entry, please update.
Also, please open a corresponding PR in `sdk-nrf` with a manifest update.

**Comment by edmont** [comment]
@rlubos the authoring information should be fine now.

**Comment by edmont** [comment]
Closing since it's not needed after the upmerge.

**Pull request closed without merging**
