### PR TITLE
[v1.4.1] Backport #28143 from upstream

### PR DESCRIPTION
**Pull request by carlescufi**
https://github.com/zephyrproject-rtos/zephyr/pull/28143

### CODE REVIEW

**Comment by carlescufi** [comment]
CC @alextsam

**Comment by alextsam** [comment]
@carlescufi thanks for this!
I see that gitlint complains about the line sizes after the addition of "[nrf fromtree] ". Should I do something about this in order to get the PR merged?
Thanks!

**Comment by carlescufi** [comment]
@joerchan could you please include this in https://github.com/nrfconnect/sdk-nrf/pull/3312 ?

**Comment by joerchan** [comment]
> @joerchan could you please include this in [nrfconnect/sdk-nrf#3312](https://github.com/nrfconnect/sdk-nrf/pull/3312) ?

These commits are now in this PR: https://github.com/nrfconnect/sdk-zephyr/pull/391

**Pull request closed without merging**
