### PR TITLE
LwM2M plain CBOR content format support

### PR DESCRIPTION
**Pull request by VeijoPesonen**
Just to make clear this content format shouldn't be confused with LwM2M CBOR which is introduced in LwM2M v1.2.  Plain CBOR content format is part of the LwM2M version 1.1.

The content format can be pushed to upstream zephyr once the ZCBOR CBOR library has been upstreamed too.

### CODE REVIEW

**Comment by VeijoPesonen** [comment]
@SeppoTakalo, @jarlamsa for your information

**Comment by VeijoPesonen** [comment]
I'll add a changelog entry once people are happy with the changes otherwise. Saves me some trouble when there is no need to rebase so often.

**Review by SeppoTakalo — APPROVED** [review]

**Comment by VeijoPesonen** [comment]
I attached the reason why these are NCS-only commits to each commit message separately.

**Comment by rlubos** [comment]
> This is a noup patch because zcbor support is NCS-only.

That's no longer the case, zcbor is now part of the upstream (https://github.com/zephyrproject-rtos/zephyr/commit/22c32cfbb473af2251cbd46396d8223ca404d0c0). Please submit an upstream PR and make those commits `[nrf fromlist]`.

**Comment by VeijoPesonen** [comment]
> > This is a noup patch because zcbor support is NCS-only.
> 
> That's no longer the case, zcbor is now part of the upstream ([zephyrproject-rtos/zephyr@22c32cf](https://github.com/zephyrproject-rtos/zephyr/commit/22c32cfbb473af2251cbd46396d8223ca404d0c0)). Please submit an upstream PR and make those commits `[nrf fromlist]`.

Done, please see the PR zephyrproject-rtos/zephyr#44943

**Comment by jheiskan81** [comment]
@VeijoPesonen Is this PR added Put and get time new API?

**Comment by VeijoPesonen** [comment]
Replace with #789.

**Pull request closed without merging**
