### PR TITLE
[nrf fromtree] drivers: qspi: added operation timeout

### PR DESCRIPTION
**Pull request by hlord2000**
Added Kconfig assignment of qspi timeout.
Per nrfx v3.2 addition of qspi timeout in config
struct.

Previous: https://github.com/nrfconnect/sdk-zephyr/pull/1428

### CODE REVIEW

**Review by de-nordic — CHANGES_REQUESTED** [review]
Missing [nrf fromtree] tag and reference to upstream commit.

Cherry pick the commit with:
git cherry pick —signoff -x
and amend the title line with tag.

**Comment by de-nordic** [comment]
There is now https://github.com/nrfconnect/sdk-zephyr/pull/1454, do you want to proceed with your PR or can you coin review there?

**Comment by hlord2000** [comment]
> @hlord2000 There is now #1454, do you want to proceed with your PR or can you coin review there?

I will proceed with my PR as it addresses a separate issue. Will fix shortly.

**Comment by de-nordic** [comment]
> > @hlord2000 There is now #1454, do you want to proceed with your PR or can you coin review there?
> 
> I will proceed with my PR as it addresses a separate issue. Will fix shortly.

Ah sorry. Somehow I have managed to open the same issue twice and thought that these are the same.

**Comment by hlord2000** [comment]
> > > @hlord2000 There is now #1454, do you want to proceed with your PR or can you coin review there?
> > 
> > 
> > I will proceed with my PR as it addresses a separate issue. Will fix shortly.
> 
> Ah sorry. Somehow I have managed to open the same issue twice and thought that these are the same.

Just updated. Any further changes required? Thanks!

**Comment by de-nordic** [comment]
> > > > @hlord2000 There is now #1454, do you want to proceed with your PR or can you coin review there?
> > > 
> > > 
> > > I will proceed with my PR as it addresses a separate issue. Will fix shortly.
> > 
> > 
> > Ah sorry. Somehow I have managed to open the same issue twice and thought that these are the same.
> 
> Just updated. Any further changes required? Thanks!

You need one more PR, to the sdk-nrf, that will introduce the change. Something like
https://github.com/nrfconnect/sdk-nrf/pull/13667
so that the change gets tested, and then applied, to sdk-nrf.

**Comment by hlord2000** [comment]
> > > > > @hlord2000 There is now #1454, do you want to proceed with your PR or can you coin review there?
> > > > 
> > > > 
> > > > I will proceed with my PR as it addresses a separate issue. Will fix shortly.
> > > 
> > > 
> > > Ah sorry. Somehow I have managed to open the same issue twice and thought that these are the same.
> > 
> > 
> > Just updated. Any further changes required? Thanks!
> 
> You need one more PR, to the sdk-nrf, that will introduce the change. Something like [nrfconnect/sdk-nrf#13667](https://github.com/nrfconnect/sdk-nrf/pull/13667) so that the change gets tested, and then applied, to sdk-nrf.

https://github.com/nrfconnect/sdk-nrf/pull/13697

**Comment by hlord2000** [comment]
Hello @de-nordic are there any changes required from the sdk-nrf PR?

**Comment by de-nordic** [comment]
> Hello @de-nordic are there any changes required from the sdk-nrf PR?

Fix the west, because it conflicts, and take it out of draft.

**Review by de-nordic — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Comment by de-nordic** [comment]
@hlord2000 You need to rebase this to the latest sdk-zephyr that the west you have already  rebased pointed to. Right now the sdk-nrf PR keeps failing on problems unrelated to this PR.

**Comment by hlord2000** [comment]
> @hlord2000 You need to rebase this to the latest sdk-zephyr that the west you have already rebased pointed to. Right now the sdk-nrf PR keeps failing on problems unrelated to this PR.

The sdk-nrf PR is now passing. Thank you

**Pull request merged**
