### PR TITLE
Upmerge 2021 07 26

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
Status
------

Awaiting +1 or -1.

Reverted and reapplied
----------------------

This is a list of reverted patches that were reapplied after the
mergeup commit, in no particular order. Some of them were squashed
into other commits or had their shortlogs changed. Conflict resolution
was done as needed.

* e29515afd9 [nrf noup]: Remove "toup" and "temphack" from sauce tags
* 79c07819c3 [nrf noup] ci: Compliance workflow downstream tweaks
* 6c7c360a9a [nrf noup] dts: Adding cryptocell_sw as chosen entropy
* 44b243cc01 [nrf temphack] boards: arm: nrf5340: disable TF-M on non-secure builds
* 6b81e7cff7 [nrf temphack] soc: nrf: Switch null-pointer detection option to MPU
* 5db7cb24c0 [nrf noup] Bluetoooth: Add experimental for non-qualified options
* 05837f70ac [nrf noup] include: net: add TCP sesstimeo socket option
* 5b2f44fa72 [nrf noup] net: sockets: Add new DTLS and RAI socket options
* 5f87c2967a [nrf noup] net: sockets: Move NCS additions to a separate header
* ec1065c882 [nrf noup] include: net: add AI_PDNSERV flag
* e021755883 [nrf noup] include: net: add NCS extensions
* 938c7d44af [nrf noup] boards: don't set BUILD_WITH_TFM default for 91ns
* 02f76ba0e9 [nrf fromlist] modules: tfm: add configuration for disabling the RNG module
* c1e71016c5 [nrf toup] modules: mbedtls: Provide 3rd option for MBEDTLS configuration
* 71ee2945e9 [nrf toup] modules: tfm: Override the TF-M MBEDCRYPTO_PATH
* e22a7803db [nrf temphack]: Limit number of parallel jobs for TF-M build to 1

Left as-is, in place
--------------------

These patches are left as-is before the mergeup commit, as they did
not conflict with anything upstream.

* 28e2001ef2 [nrf temphack] kconfig: Disallow FPU for SPM
* 2f39f35b1b [nrf temphack] bluetooth: Bluetooth configuration for RPC
* 0c1f3a498a [nrf noup] tfm: adapt ieee802154_nrf5 driver to TFM
* c43ab78056 [nrf noup] Bluetoooth: host: Update experimental for qualification
* e6435eeabb [nrf temphack] samples: echo_server: remove mbed TLS settings for TF-M
* b3c18c135a [nrf temphack]: Adding TF-M Kconfig fragment for echo_server
* a2d0436cdb [nrf noup] codeowners: Remove .known-issues
* 11e5d94c98 [nrf noup]: Bluetooth: samples: Add dynamic power control
* add338c9c7 [nrf noup] tree-wide: support NCS Partition Manager (PM) definitions
* 0f5d5543dd [nrf noup] ci: Add Jenkins-based CI for zephyr
* 3a744b5d8f [nrf noup] drivers: ieee802154: Use nRF Secure Services to read EUI64
* 70ca5d3f11 [nrf noup] dts: add binding file for cc132 cryptocell sw
* e5356c0c05 [nrf temphack] setting `ZEPHYR_<MODULE_NAME>_KCONFIG` for NCS modules
* fc9e778743 [nrf noup] dts: prefer CC310 for zephyr,entropy
* cf804b8102 [nrf noup] dts: add compatibles for CC310 NS access
* cc3b083d41 [nrf noup] net: l2: Kconfig: Add option for Zigbee L2 layer
* 053073e000 [nrf noup] net: lib: mqtt: Provide option to enable TLS session caching

Replaced
--------

* 3d51dad9c8 [nrf noup] doc: Share Kconfig documentation between repos
  Replaced with `[nrf noup] doc: remove Kconfig reference`
* 1dcdc85aba [nrf temphack] tfm: Kconfig: Disable TFM_BL2 when using CryptoCell
  Replaced with `[nrf noup] tfm: Kconfig: Disable TFM_BL2 when using CryptoCell`

Reverted permanently
--------------------

These are no longer needed as far as I can tell.

There are currently many downstream commits in sdk-zephyr, because we
last forked off of an upstream RC and subsequently had to cherry pick
a lot of fixes for NCS v1.6.0. There are therefore a lot of reverts in
this list.

* a7f71e0836 [nrf temphack] Revert "modules: tfm: cleanup redundant Kconfig... @andvib confirms not needed
* d62a6ad15d [nrf temphack] tfm: Kconfig: Disable TFM_BL2 when using CryptoCell 
* 96dc6af11c [nrf temphack] modules: tfm: Pass ZEPHYR_BASE to TFM build
* 0944459b5b [nrf fromtree] manifest: update openthread
* 7c0e0b97d5 [nrf fromtree] boards: thingy53: start network core before 802.15.4 driver
* a62ea8fa29 [nrf fromlist] net: openthread: remove unneded Kconfig dependency
* f6426813b8 [nrf fromlist] drivers: serial: nrfx: Add pullups to RXD and CTS
* fb22d538bb [nrf fromlist] drivers: ieee802154: fix unintentional case fall-through
* 384ff0c232 [nrf fromtree] Bluetooth: controller: Fix initial empty flag for ...
* 9b0cf7828f [nrf fromtree] Bluetooth: controller: Check length field of scan ...
* d120ab1daf [nrf fromlist] Bluetooth: L2CAP: Fix missing net_buf_unref()
* 960491d1f4 [nrf fromtree] Bluetooth: host: Prevent race condition in ...
* ad0dd41e0c [nrf fromlist] soc: nrf53: Fix configuration of HFXO capacitance
* d94780be5b [nrf fromtree] modules: trusted-firmware-m: Set TF-M isolation level
* 829d32cd7c [nrf fromtree] drivers: nrf_rtc_timer: Remove unnecessary locking
* e7a6eded2e [nrf fromtree] kernel: timeout: Fix adding of an absolute timeout
* cfeafe5f10 [nrf fromtree] task_wdt: Pause hardware wdt during debugging
* 683d25df8e [nrf fromtree] samples: drivers: watchdog: Pause during debugging
* cc81eda41a [nrf fromtree] manifest: update hal_nordic
* a8f3c1dabb [nrf fromtree] drivers: ieee802154: propagate frame counter to upper layer
* 9ba10efc5f [nrf fromtree] drivers: ieee802154: copy back the TX buffer into the upper
* af79106e4a [nrf fromtree] modules: hal_nordic: Update nrfx to have doc fixes
* e22d8bbb73 [nrf fromtree] tfm: Put saving of FPU context into its own file so ...
* a53f4eb32f [nrf fromtree] tests: arm_thread_swap_tz: Enhance testing of FP ...
* 16979c6a74 [nrf fromtree] tfm: interface: Fix bug where FPU registers were not ...
* a9993c736e [nrf fromtree] Bluetooth: host: Optionally disable GATT sec re-establish
* 74462e3a80 [nrf fromlist] soc: Tune capacitor for LFXO for nRF53 and update accuracy
* 9cdc396ef9 [nrf fromtree] soc: nrf53: Add options for HFXO/LFXO load capacitance
* c6852b6ebf [nrf fromlist] modules: tf-m: split configuration into multiple ...
* 8c6ba95eaf [nrf toup] drivers: ieee802154: add CSL receiver for nRF5
* e3508a4a6b [nrf fromtree] drivers: serial: nrf_uarte: Fix async/int TX api
* 0b0c867e74 [nrf fromtree] drivers: ieee802154: include timestamp in acks
* 499addae67 [nrf fromlist] drivers: ieee802154: configure IE header injection for nRF5
* 669c59eb3b [nrf fromtree] drivers: ieee802154: fix ACK length handling
* 5957912a66 [nrf fromlist] drivers: ieee802154: add support for secured transmission
* a99556eb63 [nrf fromtree] drivers: ieee802154: make keys management API generic
* e7b3c1bc03 [nrf fromtree] drivers: ieee802154: replace enh ack probing with
* b31c310199 [nrf fromtree] net: openthread: add option to configure software
* 39f3d4acd1 [nrf fromtree] net: openthread: Fix multiple Kconfig enablers for
* c3ea04325c [nrf fromtree] modules: tf-m: fix NS image selection for regression tests
* 600e2350cf [nrf fromlist] Bluetooth: Mesh: Add API to manually store pending RPL
* 18630e1a42 [nrf fromtree] doc: reference: Add a section for the C standard library
* ae27f9b0bc [nrf fromtree] ci: Add an errno.h check to CI
* 7996cbdf48 [nrf fromtree] libc: minimal: Add EOVERFLOW
* e5d3939f07 [nrf fromtree] libc: minimal: Add doxygen formatting to errno.h
* 2a6f92a094 [nrf fromtree] libc: minimal: Align errno.h values with newlib
* d81b686790 [nrf fromtree] Bluetooth: Mesh: Reject identical public keys
* e5a9c3b199 [nrf fromtree] Bluetooth: Mesh: Add information about secure
* 35f86f6e9d [nrf toup] samples: tf-m: remove CONFIG_TFM_PARTITION_AUDIT_LOG=n
* 744a353d5b [nrf fromtree] soc: arm: nordic_nrf: nrf53: Fix flash page erase time
* 3567af1ab7 [nrf fromlist] samples: net: Increase stack sizes for echo client/server
* 05169debbc [nrf fromlist] drivers: ieee802154: extend capabilities
* 9e2f10d59a [nrf fromlist] net: openthread: set ieee802154_frame_retry flag
* 24700b8424 [nrf fromlist] drivers: ieee802154: add option to retransmit a frame
* 6577386abe [nrf fromlist] net: pkt: add ieee802154_frame_retry field
* f99237b968 [nrf fromlist] modules: tfm: add option for selecting crypto modules
* 2510220615 [nrf fromtree] Bluetooth: Host: change error returned when ...
* b692f4de5c [nrf fromtree] Bluetooth: Host: do not overwrite result in ...
* 9552ebe600 [nrf fromtree] Bluetooth: Host: add missing zero CIDs in ecred_conn_req
* 627af7a5e8 [nrf fromtree] Bluetooth: host: Reject remote public key on same X ...
* 659200368d [nrf fromtree] Bluetooth: host: Notify application about prepare ...
* 8e1d369039 [nrf fromtree] Bluetooth: host:l2cap: fix sending error in ...
* 5ae534f564 [nrf fromtree] Bluetooth: host: Fix extended advertising feature bit ...
* 0970aa156a [nrf fromtree] Bluetooth: host: Fix disconnect priority event handling
* 93c6f394eb [nrf fromtree] Bluetooth: host: Fix L2CAP sent callback on ...
* be299d5714 [nrf fromtree] Bluetooth: host: Add check for already enabled in ...
* c66761d325 [nrf fromtree] Bluetooth: host: Fix multiple advertisers with ...
* 20ba4c2011 [nrf fromtree] Bluetooth: gatt: cancel all prepared writes on invalid ..
* 278d206b48 [nrf fromtree] Bluetooth: Mesh: Don't reset PB ADV reliable timer on
* c54a36a091 [nrf fromtree] Bluetooth: Mesh: Remove outated RPL entry from persistent
* 2446b00163 [nrf fromtree] Bluetooth: Mesh: Change friend_cred decision point to
* 896e741ecd [nrf fromtree] Bluetooth: Mesh: Add VA flag to generic pending flags
* a098c5fbcf [nrf fromtree] Bluetooth: Mesh: Fix incorrect flag check in mesh
* 2c112c3e3c [nrf fromtree] Bluetooth: controller: Revert strict preempt ticker start
* 34ee9d67e8 [nrf fromlist] samples: tfm: Add PSA Protected Storage sample
* 1d8ce76689 [nrf fromtree] actions: clang: invoke twister with -M to keep size down
* 44e6211671 [nrf fromtree] Bluetooth: Mesh: Pass correct pointer to publish_sent
* b0e44bd8e2 [nrf fromtree] drivers: flash: nrf_qspi_nor: Fix no multithreading compilation
* 42d753ce27 [nrf fromtree] doc: improve doc processor installation
* 8009694dc5 [nrf fromtree] doc: improve installing dependencies
* 46fdb8c925 [nrf fromtree] logging: backend_rtt: Align to changes in RTT_LOCK/UNLOCK
* fd1092f746 [nrf fromtree] manifest: update segger
* 3a4763d838 [nrf fromtree] drivers: console: rtt: Add no multithreading support
* 5deeae73ce [nrf fromtree] tracing: fix conflict with RTT locking
* 05ce3ff159 [nrf fromlist] tests/logging/log_backend_fs: Fix test failed on dirty file system
* 710d284293 [nrf fromlist] arch: arm: Fix build warning
* 225b5e04de [nrf fromtree] drivers: flash: nrf_qspi_nor: Fix no multithreading configuration
* 43cb584911 [nrf fromlist] ipc: rpmsg_service: Add missing log_strdup
* da34a453f8 [nrf fromtree] Bluetooth: host: Remove cancel sync from database hash commit
* 9c4eb5773d [nrf fromtree] tfm: cmake: added CMAKE_ARGS as argument to
* 6b57c10912 [nrf fromtree] Bluetooth: controller: Fix PPIs use for nRF52805 SoC
* ce8b6d898f [nrf fromtree] soc: nrf9160: Remove incorrect indication of SWO availability
* b854636053 [nrf fromtree] drivers: serial: nrf_uarte: Fix checkpatch issues
* 125fe2f9cc [nrf fromtree] drivers: serial: nrf_uarte: Add missing check for async API
* d52e03393e [nrf fromtree] drivers: serial: nrf_uart: Disable uart when fifo_fill not used
* 0447efc066 [nrf fromtree] drivers: serial: nrf uarte: Fix for the RX byte counter
* 8ccca1577c [nrf fromtree] kernel: move thread_stack.h to include/kernel
* bd03de6675 [nrf fromtree] doc: kernel: thread stack is not the same as stack object
* 9991e781a3 [nrf fromtree] drivers: eth_enc424j600: explicitly disable INTIE after reset
* 8a4e0bb8d2 [nrf fromtree] drivers: eth_enc424j600: terminate driver thread only when debugging
* 653e4065cd [nrf fromtree] net: enable TX thread if USB device support is enabled
* ff8165e5a5 [nrf fromtree] tests: drivers: uart: Add test for uart power management
* 64783fe89a [nrf fromtree] drivers: serial: nrf_uarte: Fix uart_callback_set unsupported handling
* 321273c53d [nrf fromtree] drivers: serial: nrf_uarte: Fix power management transitions
* d8e6787c98 [nrf fromtree] doc: extensions: doxyrunner: make html output optional
* 98444ff5a3 [nrf fromtree] doc: enable members option by default when using breathe
* d530426aa0 [nrf fromtree] drivers: display: fix doxygen issues
* 342035ad48 [nrf fromtree] doc: warnings: make expressions more generic
* 340bfce7da [nrf fromtree] doc: doxygen: do not use separate member pages
* c677144383 [nrf fromtree] doc: doxygen: make relative paths absolute
* 32c550b1f3 [nrf fromtree] doc: remove redundant breathe project
* 80f2df7eab [nrf fromtree] doc: conf: remove unused breathe project
* b3bf562b73 [nrf fromtree] doc: make some Sphinx config path absolute
* ace4c168d0 [nrf fromtree] doc: scripts: gen_kconfig_rest: fix rendering issues
* 19f27783a5 [nrf fromtree] doc: scripts: gen_kconfig_rest: add workaround for page width
* 50c2c9876b [nrf fromtree] drivers: timer: sys_clock: return -ENOSYS if not implemented
* 3eb4cac1f3 [nrf fromtree] pm: device: check for ENOSYS
* 35f6819eaa [nrf fromtree] samples: pm: Fix device pm sample
* de0239ab48 [nrf fromtree] tests: interrupt: refine the offload case not rely on delay timing
* 44c5739ce3 [nrf fromtree] adc_emul: case can not run on native_posix board
* b45c3199a6 [nrf fromtree] net: tcp: Change locking order in connection establishment
* c7ef9ab98e [nrf fromtree] drivers: led_pwm: Update pm_control function
* 8468bb0253 [nrf fromlist] lib: os: cbprintf: Add ARG_UNUSED to unused arguments
* 2d77214ebc [nrf fromlist] lib: os: cbprintf: Add missing initialization of structure fields
* fca8c5653f [nrf fromlist] logging: Add missing initialization of structure fields
* ac1665226f [nrf fromtree] boards: thingy53: Fix building issue with NS image.
* 1b8eebeb19 [nrf fromtree] kernel: work: fix race condition with cancel before work runs
* 970ea065d0 [nrf fromlist] net: sockets: tls: Use secure random generator from Zephyr
* 6c189f6bfc [nrf fromlist] samples: boards: nrf: ieee802154: set RTC user channels

### CODE REVIEW

**Comment by hakonfam** [comment]
> * [96dc6af](https://github.com/nrfconnect/sdk-zephyr/commit/96dc6af11cf2e5e04aeca96ac6a37642257fd1f6) [nrf temphack] modules: tfm: Pass ZEPHYR_BASE to TFM build

Is needed, but it seems that we have a rather large diff on this file compared to upstream, so we might want to keep this patch.


```
diff --git a/modules/trusted-firmware-m/CMakeLists.txt b/modules/trusted-firmware-m/CMakeLists.txt
index 9e11eded7e..b6453f9a33 100644
--- a/modules/trusted-firmware-m/CMakeLists.txt
+++ b/modules/trusted-firmware-m/CMakeLists.txt
@@ -188,6 +188,7 @@ if (CONFIG_BUILD_WITH_TFM)
       -DMBEDCRYPTO_PATH=$<IF:$<BOOL:$<TARGET_PROPERTY:zephyr_property_target,TFM_MBEDCRYPTO_PATH>>,$<TAR
GET_PROPERTY:zephyr_property_target,TFM_MBEDCRYPTO_PATH>,${ZEPHYR_TRUSTED_FIRMWARE_M_MODULE_DIR}/../../cr
ypto/mbedtls/mbedtls>
       -DMCUBOOT_PATH=${ZEPHYR_TRUSTED_FIRMWARE_M_MODULE_DIR}/../tfm-mcuboot
       -DPSA_ARCH_TESTS_PATH=${ZEPHYR_TRUSTED_FIRMWARE_M_MODULE_DIR}/psa-arch-tests
+      -DZEPHYR_BASE=${ZEPHYR_BASE}
       ${ZEPHYR_TRUSTED_FIRMWARE_M_MODULE_DIR}/trusted-firmware-m
     WORKING_DIRECTORY ${TFM_BINARY_DIR}
     COMMAND_EXPAND_LISTS

```

**Comment by mbolivar-nordic** [comment]
> Needs triaging/resolution
> 
>     * [1dcdc85](https://github.com/nrfconnect/sdk-zephyr/commit/1dcdc85abae7e991007ae3ffeb68c3882a5ae6f6) [nrf temphack] tfm: Kconfig: Disable TFM_BL2 when using CryptoCell
> 
>     * [d62a6ad](https://github.com/nrfconnect/sdk-zephyr/commit/d62a6ad15d68c8f63328a93cc123a90826024609) [nrf temphack] tfm: Kconfig: Disable TFM_BL2 when using CryptoCell
> 
>     * [96dc6af](https://github.com/nrfconnect/sdk-zephyr/commit/96dc6af11cf2e5e04aeca96ac6a37642257fd1f6) [nrf temphack] modules: tfm: Pass ZEPHYR_BASE to TFM build
> 
>     * [a7f71e0](https://github.com/nrfconnect/sdk-zephyr/commit/a7f71e0836470660272f081e65504d8278674cc0) [nrf temphack] Revert "modules: tfm: cleanup redundant Kconfig...

@hakonfam @oyvindronningstad @anangl ping

**Comment by mbolivar-nordic** [comment]
Whoops, sorry @hakonfam -- I missed your response.

**Comment by mbolivar-nordic** [comment]
>>  96dc6af [nrf temphack] modules: tfm: Pass ZEPHYR_BASE to TFM build
>
> Is needed, but it seems that we have a rather large diff on this file compared to upstream, 
> we might want to keep this patch since any [fromlist] would be hard to integrate smoothly (by the looks of it).
> The following patch should work on top of the upmerge.

@hakonfam OK, are you saying this should go upstream? It was originally categorized as a temphack, but you mention fromlist in your response, so I'm a bit confused.

I can't tell from the downstream commit log what kind of use case it'd be useful for upstream. It just mentions building out of tree boards, which I'm guessing are out of tree with respect to TF-M, not zephyr? I'm not familiar with the TF-M build system so I'm not sure what this patch is doing.

Can you send a fromlist to upstream zephyr if it's appropriate along with a backport here? It looks like the relevant lines around that hunk are very similar and it's a one-liner, so conflict resolution should be manageable. If we can track it as a fromlist and it's merged ups tream, then the next person doing an upmerge will just revert the [nrf fromlist] before doing the upmerge and we should be all set.

I also see multiple ways to potentially extend the arguments passed to TF-M. This one in particular looks like it might be useful:

```
      $<GENEX_EVAL:$<TARGET_PROPERTY:zephyr_property_target,TFM_CMAKE_OPTIONS>>
```

Is there some way to just tack something onto that property to do what we need without a downstream patch?

> Why isn't this commit included in the upmerge? zephyrproject-rtos/zephyr@583d5a6

Not sure what you mean. It is included:

```
$ git log -4 --oneline modules/trusted-firmware-m/CMakeLists.txt
583b5cf04e [nrf noup] Limit number of parallel jobs for TF-M build to 1
7df1cc2a9f [nrf fromlist] modules: tfm: Override the TF-M MBEDCRYPTO_PATH
545795ccea [nrf fromlist] modules: tfm: add configuration for disabling the RNG module
583d5a6db3 tfm: Refactor the TF-M Cmake code to simplify and remove the function
```

> Need triaging / resolution
>
> a7f71e0 [nrf temphack] Revert "modules: tfm: cleanup redundant Kconfig...

How about this one? I reverted the temphack. Is it still needed?

**Comment by mbolivar-nordic** [comment]
> 1dcdc85 [nrf temphack] tfm: Kconfig: Disable TFM_BL2 when using CryptoCell
> d62a6ad [nrf temphack] tfm: Kconfig: Disable TFM_BL2 when using CryptoCell

@oyvindronningstad ping on this. Can you confirm that the reverts are OK or say what we should do here if they are still needed?

**Comment by hakonfam** [comment]
> > > [96dc6af](https://github.com/nrfconnect/sdk-zephyr/commit/96dc6af11cf2e5e04aeca96ac6a37642257fd1f6) [nrf temphack] modules: tfm: Pass ZEPHYR_BASE to TFM build
> > 
> > 
> > Is needed, but it seems that we have a rather large diff on this file compared to upstream,
> > we might want to keep this patch since any [fromlist] would be hard to integrate smoothly (by the looks of it).
> > The following patch should work on top of the upmerge.
> 
> @hakonfam OK, are you saying this should go upstream? It was originally categorized as a temphack, but you mention fromlist in your response, so I'm a bit confused.

I was referring to commit 583d5a6 which I claimed to be missing, but then it was not missing.

> I can't tell from the downstream commit log what kind of use case it'd be useful for upstream. It just mentions building out of tree boards, which I'm guessing are out of tree with respect to TF-M, not zephyr? I'm not familiar with the TF-M build system so I'm not sure what this patch is doing.
> 
> Can you send a fromlist to upstream zephyr if it's appropriate along with a backport here? It looks like the relevant lines around that hunk are very similar and it's a one-liner, so conflict resolution should be manageable. If we can track it as a fromlist and it's merged ups tream, then the next person doing an upmerge will just revert the [nrf fromlist] before doing the upmerge and we should be all set.
> 
> I also see multiple ways to potentially extend the arguments passed to TF-M. This one in particular looks like it might be useful:
> 
> ```
>       $<GENEX_EVAL:$<TARGET_PROPERTY:zephyr_property_target,TFM_CMAKE_OPTIONS>>
> ```
> 
> Is there some way to just tack something onto that property to do what we need without a downstream patch?

I will try to come up with a solution for that.

> > Why isn't this commit included in the upmerge? [zephyrproject-rtos/zephyr@583d5a6](https://github.com/zephyrproject-rtos/zephyr/commit/583d5a6)
> 
> Not sure what you mean. It is included:

Good, I didn't see it in my initial version of the upmerge PR, maybe I was having issues syncing my repos.

 
> > Need triaging / resolution
> > [a7f71e0](https://github.com/nrfconnect/sdk-zephyr/commit/a7f71e0836470660272f081e65504d8278674cc0) [nrf temphack] Revert "modules: tfm: cleanup redundant Kconfig...
> 
> How about this one? I reverted the temphack. Is it still needed?

I will investigate this today.

**Comment by hakonfam** [comment]
Here is a fix for 96dc6af11cf2e5e04aeca96ac6a37642257fd1f6 https://github.com/mbolivar-nordic/sdk-nrf/pull/8 
 
 
Same fix on nrf https://github.com/nrfconnect/sdk-nrf/pull/5253

**Comment by hakonfam** [comment]
I verified that 1dcdc85abae7e991007ae3ffeb68c3882a5ae6f6 is still needed. I will look into why it fails, but I doubt that we will be able to come up with a solution within the timeframe of this upmerge.

**Comment by hakonfam** [comment]
@andvib  is executing the TF-M test suite to verify that a7f71e0 is no longer needed.

**Review by de-nordic — APPROVED** [review]
Tested mcumgr and mcuboot for the upmerge on nrf52840dk, everything seem to work ok (or at least is not more broken).

Looks OK.

**Comment by mbolivar-nordic** [comment]
@hakonfam thanks for your help. Here is what I understood:

- 96dc6af: @hakonfam made this unnecessary via `modules: tfm: pass ZEPHYR_BASE to TF-M build` in https://github.com/nrfconnect/sdk-nrf/pull/5189
- 1dcdc85: @hakonfam confirms this is still needed; I reapplied it as 78cb330ca8
- d62a6ad: I left this permanently reverted, as 1dcdc85 was a replacement for it
- a7f71e0: @andvib is verifying that this is no longer needed

I'll update the giant PR description too, but I wanted you to have this summary in case I missed anything.

**Comment by mbolivar-nordic** [comment]
>     * @andvib is verifying that this is no longer needed

Any update?

**Comment by andvib** [comment]
@mbolivar AFAIK TF-M is still broken in the upmerge, so I can't confirm yet

**Comment by edmont** [comment]
@mbolivar these changes are required to fix KRKNWK-11089 issues: https://github.com/nrfconnect/sdk-nrf/pull/5298

May you please cherry-pick them?

**Comment by andvib** [comment]
@mbolivar Finally I've been able to verify that a7f71e0 is no longer needed 🥳

**Comment by mbolivar-nordic** [comment]
> @mbolivar Finally I've been able to verify that [a7f71e0](https://github.com/nrfconnect/sdk-zephyr/commit/a7f71e0836470660272f081e65504d8278674cc0) is no longer needed partying_face

Thanks! Please take note my work handle is @mbolivar-nordic :)

**Comment by mbolivar-nordic** [comment]
> May you please cherry-pick them?

@edmont OK, I will have a look, but in the future please send pull requests to my upmerge branches as I've been requesting in my internal status update emails.

**Review by nvlsianpu — APPROVED** [review]

**Review by tejlmand — COMMENTED** [review]
> 2f39f35 [nrf temphack] bluetooth: Bluetooth configuration for RPC

I'm not fond of the `[temphack]` https://github.com/nrfconnect/sdk-zephyr/commit/2f39f35b1b7d1fbc1813606a435f410b7f74960b still being present.

At release meeting for v1.6.0 it was clearly stated that this commit was only accepted because it was close to v1.6.0 relase date and RPC feature was highly desired to have in the v1.6 relase.

It was a clearly stated that this commit had to be re-worked before v1.7.0 and there is even a Jira for this: NCSDK-10028.
And it's even mentioned in the original PR:
https://github.com/nrfconnect/sdk-zephyr/pull/485#issuecomment-858762020

Of course before v1.7.0 is not the same as before this upmerge, but would still like to raise this unfix issue.

**Comment by mbolivar-nordic** [comment]
> Of course before v1.7.0 is not the same as before this upmerge, but would still like to raise this unfix issue.

I agree with you, but I don't think it should block the upmerge. I think @shantha-14 and @carlescufi need to decide how to handle this by release time.

**Review by tejlmand — APPROVED** [review]
> 
> 
> > Of course before v1.7.0 is not the same as before this upmerge, but would still like to raise this unfix issue.
> 
> I agree with you, but I don't think it should block the upmerge. I think @shantha-14 and @carlescufi need to decide how to handle this by release time.

Thanks for fast reply, and I agree with you.
Just needed a second to this issue.
+1 for the upmerge.

**Pull request merged**
