### PR TITLE
boards: nordic: Update PWM configuration to follow zephy upstream

### PR DESCRIPTION
**Pull request by kl-cruz**
Update nRF54 DKs with changes taken from zephyr upstream.

### CODE REVIEW

**Comment by ludvigsj** [comment]
I believe you have missed the polarity of `pwm_led1` (in `nrf54l15pdk_nrf54l15-common.dtsi`) which has changed in upstream but is still `INVERTED` here in sdk-zephyr? Or am I not reading things right?

**Comment by ludvigsj** [comment]
For info: without this we (BLE Mesh) have a sample with a non-functioning LED when running on nrf54L15, it would be nice if this could get in for NCS 2.7.0 (meaning: added to the milestone) so we have a fully functional sample, but this won't block the release for our case.

**Comment by miha-nordic** [comment]
@kl-cruz is there sdk-nrf manifest update PR?

**Comment by kl-cruz** [comment]
@miha-nordic I will prepare

**Review by carlescufi — CHANGES_REQUESTED** [review]
why is this a `noup`? why do the pins change between up and downstream?

**Review by gmarull — CHANGES_REQUESTED** [review]
can't be a noup

**Review by gmarull — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
