### PR TITLE
nRF5340 multiprotocol fixes

### PR DESCRIPTION
**Pull request by hubertmis**
The cherry-picked commits originate from zephyrproject-rtos/zephyr#31474

This PR suppresses #439 and #435

### CODE REVIEW

**Comment by jciupis** [comment]
@hubertmis Please have a look at [this comment](https://github.com/nrfconnect/sdk-zephyr/pull/435/#discussion_r569649575) and update the commit message accordingly

**Review by jciupis — APPROVED** [review]

**Review by czeslawmakarski — APPROVED** [review]

**Review by carlescufi — CHANGES_REQUESTED** [review]
Why is there a `noup` in this series? We should really do it `fromlist`?

**Comment by jciupis** [comment]
@carlescufi the commit marked as `noup` modifies code that is not present in upstream at all. It contains a fix for an older `noup` commit.

**Comment by hubertmis** [comment]
> @carlescufi the commit marked as `noup` modifies code that is not present in upstream at all.

I agree we should fix in by porting this port upstream. However to do that we need some upstream configuration (Kconfigs?) to detect that SPM is not present upstream. AFAIK, there is no such configuration upstream now.

**Comment by carlescufi** [comment]
> > @carlescufi the commit marked as `noup` modifies code that is not present in upstream at all.
> 
> I agree we should fix in by porting this port upstream. However to do that we need some upstream configuration (Kconfigs?) to detect that SPM is not present upstream. AFAIK, there is no such configuration upstream now.

SPM? This was a missing semicolon: https://github.com/nrfconnect/sdk-zephyr/pull/445/commits/57f98379b9736649537e74f796115fa14a15fbe7

**Comment by carlescufi** [comment]
Oh gotcha @hubertmis and @jciupis. In that case, can you please add in the commit message of that `noup` a reference to the other `noup` commit that this one modifies please? That way they can be squashed together on the next rebase.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
> This PR suppresses #439 and #435

@hubertmis please close those now.

**Review by ioannisg — APPROVED** [review]
Looks fine, we only have from-tree patches (we need @anangl approval i think)
(The noup patch is trivial.)

**Review by anangl — APPROVED** [review]

**Pull request merged**
