### PR TITLE
[nrf fromtree] Bluetooth: Mesh: Fix missing model extensions

### PR DESCRIPTION
**Pull request by ludvigsj**
PR adds extension of the configuration model server by private beacon server and large composition data server.
According to Mesh Protocol specification v 1.1
4.4.11.1
The Mesh Private Beacon Server model is a main model
that extends the Configuration Server model.
4.4.21.1
The Large Composition Data Server is a main model
that extends the Configuration Server model.

### CODE REVIEW

**Review by alxelax — APPROVED** [review]

**Review by HaavardRei — APPROVED** [review]

**Comment by ludvigsj** [comment]
Manifest PR: https://github.com/nrfconnect/sdk-nrf/pull/16160

**Comment by ludvigsj** [comment]
DNM until we have checked that this still passes qualification tests. Will remove from milestone if this takes too long

**Review by omkar3141 — APPROVED** [review]

**Comment by shanthanordic** [comment]
Is this really abug fix or feature extension, may be too late to enter the NCS Train.

**Comment by ludvigsj** [comment]
> Is this really abug fix or feature extension, may be too late to enter the NCS Train.

It is a bug fix, "extension" here means "entry in Composition Data Page about the fact that one model extends another" and is a Mesh term, it is not an extension of functionality. Since we are late with this, I guess it's up to you whether this can go in to 2.7.0 or not, but it _is_ indeed a bug fix

**Comment by alxelax** [comment]
> Is this really abug fix or feature extension, may be too late to enter the NCS Train.

@shanthanordic, not extended models do not share subscription addresses with each other. If some state changes value the bound state changes will not be published.

**Pull request merged**
