### PR TITLE
[nrf toup] samples: 802154_rpmsg: Remove redundant kconfig

### PR DESCRIPTION
**Pull request by czeslawmakarski**
This commit removes the obsolete hardcoded kconfig in the
802154_rpmsg sample.

Signed-off-by: Czeslaw Makarski <Czeslaw.Makarski@nordicsemi.no>

### CODE REVIEW

**Review by JakubPegza — APPROVED** [review]

**Review by hubertmis — APPROVED** [review]

**Review by jciupis — APPROVED** [review]

**Comment by lmaciejonczyk** [comment]
@rlubos Reference sdk-zephyr PR: https://github.com/nrfconnect/sdk-nrf/pull/3838 is green we can merge this one.

**Review by rlubos — APPROVED** [review]

**Comment by rlubos** [comment]
Need one more approval here.

**Review by carlescufi — CHANGES_REQUESTED** [review]
Could we turn this into a `fromlist` instead? Please post the patch upstream and then take it here.

**Comment by hubertmis** [comment]
> Please post the patch upstream and then take it here.

It's actually posted here: https://github.com/zephyrproject-rtos/zephyr/pull/31474/commits/80fe71f287d274a470a3c09f927c5cc238ffe925
But most probably won't be merged within NCS 1.5 timeline. Is it enough to change to `fromlist`?

**Comment by jciupis** [comment]
@carlescufi Done. The commit has been posted in zephyrproject-rtos/zephyr#31474 as @hubertmis mentioned and now it's labelled as `fromlist` here.

**Comment by jciupis** [comment]
This PR is superseded by https://github.com/nrfconnect/sdk-zephyr/pull/454 and should be closed when https://github.com/nrfconnect/sdk-zephyr/pull/454 is merged. I'm putting the `DNM` label on it

**Comment by hubertmis** [comment]
Closing, because #456 suppressing #454 is merged now.

**Pull request closed without merging**
