### PR TITLE
nrf54l15 write block size

### PR DESCRIPTION
**Pull request by michalek-no**
write-block-size correction.

### CODE REVIEW

**Review by gchwier — APPROVED** [review]
Tested with `smp_svr` sample with enabled bluetooth.
```
Before change I received on the shell:
[00:00:00.001,283] <err> littlefs: WEST_TOPDIR/modules/fs/littlefs/lfs.c:1234: Corrupted dir pair at {0}
[00:00:00.001,290] <wrn> littlefs: can't mount (LFS -84); formatting
```

With that fix there is no warning

**Comment by gchwier** [comment]
shouldn't it go first to the Upstream repo?

**Comment by michalek-no** [comment]
> shouldn't it go first to the Upstream repo?

https://github.com/zephyrproject-rtos/zephyr/pull/70412

**Review by gchwier — APPROVED** [review]

**Comment by gchwier** [comment]
> Tested with `smp_svr` sample with enabled bluetooth.
> 
> ```
> Before change I received on the shell:
> [00:00:00.001,283] <err> littlefs: WEST_TOPDIR/modules/fs/littlefs/lfs.c:1234: Corrupted dir pair at {0}
> [00:00:00.001,290] <wrn> littlefs: can't mount (LFS -84); formatting
> ```
> 
> With that fix there is no warning

This issue is probable not related with that change. It  works the same with `write-block-size = <1>`. Warning appears after first flashing, after reset there is no warning.

**Comment by de-nordic** [comment]
> 
> This issue is probable not related with that change. It works the same with `write-block-size = <1>`. Warning appears after first flashing, after reset there is no warning.

This is normal as it fails to recognize LIttleFS in designated storage partition so makes a new one.

**Review by nvlsianpu — APPROVED** [review]

**Pull request merged**
