### PR TITLE
[nrf fromtree] net: lib: LwM2M fixes

### PR DESCRIPTION
**Pull request by tokangas**
Pull in a bunch of LwM2M fixes.

### CODE REVIEW

**Review by jheiskan81 — APPROVED** [review]
Can we cherry pick same time couple other fix?

**Comment by tokangas** [comment]
> Can we cherry pick same time couple other fix?

Maybe @rlubos can comment on that? This is the only that I know that I need. 😃

**Comment by jheiskan81** [comment]
@tokangas We can create a own PR where we add other fixies.

**Comment by rlubos** [comment]
It'd be less fuss with the manifest update if you put multiple fixes in a single PR.

**Comment by jheiskan81** [comment]
OK. I discuss with @SeppoTakalo what fixies we like to add.

**Comment by tokangas** [comment]
Added commits requested by @jheiskan81.

**Comment by tokangas** [comment]
Adding DNM label because it seems that some of the commits were cherry-picked in the wrong order and the code is broken.

**Comment by tokangas** [comment]
Three last commits would have required changes on the nrf side as well. Those have now been dropped and will be handled separately.

**Comment by jheiskan81** [comment]
Thanks @tokangas .

**Comment by tokangas** [comment]
The manifest update PR https://github.com/nrfconnect/sdk-nrf/pull/9936 is failing CI because of some openthread compilation issue:
```
../../../../../../../nrf/samples/openthread/cli/src/low_power.c: In function 'low_power_enable':
../../../../../../../nrf/samples/openthread/cli/src/low_power.c:35:9: error: 'openthread_set_state_changed_cb' is deprecated [-Werror=deprecated-declarations]
   35 |         openthread_set_state_changed_cb(on_thread_state_changed);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../../../../../../nrf/samples/openthread/cli/src/low_power.c:8:
../../../../../../../zephyr/include/zephyr/net/openthread.h:137:19: note: declared here
  137 | __deprecated void openthread_set_state_changed_cb(otStateChangedCallback cb);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
@rlubos Is this being worked on? Doesn't look it's related to these changes.

**Comment by rlubos** [comment]
The errors are visibile because sdk-zephyr and sdk-nrf are out of sync, the latest manifest update hasn't been merged yet:
https://github.com/nrfconnect/sdk-nrf/pull/9943

**Comment by tokangas** [comment]
> The errors are visibile because sdk-zephyr and sdk-nrf are out of sync, the latest manifest update hasn't been merged yet: [nrfconnect/sdk-nrf#9943](https://github.com/nrfconnect/sdk-nrf/pull/9943)

Ah, thanks, of course. My bad.

**Review by SeppoTakalo — APPROVED** [review]

**Comment by tokangas** [comment]
@rlubos Ok, now CI is passed for the manifest update PR.

**Pull request merged**
