### PR TITLE
Upmerge 05.03.2021

### PR DESCRIPTION
**Pull request by anangl**
Merge upstream up to commit 7074254937ae20f90174309b930ed8edfb53666e.

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
Merging upstream commit 3204554841db8e51fd06f8ba47f73bcdaea05fe9 does not create a conflict, but it removes an `import os` line from scripts/west_commands/runners/nrfjprog.py that we still need due to our downstream temphack 09b7569da1bfa5f0d62429dd8dde95c34611a600.

Either the temphack should be reverted and reapplied or another temphack should be put on top of the mergeup that restores the import.

**Comment by anangl** [comment]
[09b7569](https://github.com/nrfconnect/sdk-zephyr/commit/09b7569da1bfa5f0d62429dd8dde95c34611a600) reverted and re-applied after the mergeup commit, with added that missing `import os`.

**Comment by gmarull** [comment]
@anangl @carlescufi found the culprint of the documentation warning: commit 2c5b268 introduces a duplicate definition, `#define SO_SNDTIMEO 21`. The warning message did not help in this case... Should I fixup the commit or authors should do it?

**Review by joerchan — APPROVED** [review]

**Review by trond-snekvik — APPROVED** [review]

**Comment by anangl** [comment]
@gmarull I took a chance to fix that commit myself.

**Review by nvlsianpu — APPROVED** [review]

**Comment by rlubos** [comment]
> > @anangl @carlescufi found the culprit of the documentation warning: commit [2c5b268](https://github.com/nrfconnect/sdk-zephyr/commit/2c5b268460445aeeb0a3058a75efece9da7635c7) introduces a duplicate definition, `#define SO_SNDTIMEO 21`. The warning message did not help in this case... Should I fixup the commit or authors should do it?
> 
> And that's exactly why we are going to upstream that, right @rlubos? https://github.com/zephyrproject-rtos/zephyr/blame/28c823b16ee2e281f5e805140e584c63530ae58e/include/net/socket.h#L809

Actually `SO_SNDTIMEO` was recently added upstream, that's why we've got the duplicate symbol. We should remove `SO_SNDTIMEO` definition from the downstream patch linked by @anangl

**Comment by carlescufi** [comment]
> Actually `SO_SNDTIMEO` was recently added upstream, that's why we've got the duplicate symbol. We should remove `SO_SNDTIMEO` definition from the downstream patch linked by @anangl

Right, but if we didn't need to add it downstream because we've upstreamed everything we need in the sockets API, then this wouldn't have happened is what I meant.

**Review by mbolivar-nordic — APPROVED** [review]
I rechecked the structure since the mergeup commit changed due to reverting and reapplying a temphack.

Still good; linear history here for reference: https://github.com/mbolivar-nordic/fw-nrfconnect-zephyr/tree/upmerge-479-rewrite-2

(I've automated this process and we're working on making a GitHub action that will post these results automatically as part of CI.)

**Review by jfischer-no — APPROVED** [review]
Everything looks good

**Review by tejlmand — APPROVED** [review]

**Comment by anangl** [comment]
The issues (style problems) that make the compliance check fail are inherited from upstream. Nothing to be corrected in this regard here.

**Pull request merged**
