### PR TITLE
[nrf fromtree] Add support for nRF52820 in direction finding

### PR DESCRIPTION
**Pull request by ppryga**
Add support for nRF52820 in Bluetooth direction finding.
Update direction finding samples to enable support for nRF52820.

### CODE REVIEW

**Comment by ppryga** [comment]
Compliance failed on non-empty second line in commit messages.

**Review by cvinayak — APPROVED** [review]
QUICK-ACK. As this is from upstream tree.

**Comment by ppryga** [comment]
@anangl could you take a look on the PR?

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
DNM because there's no manifest update. I've requested one in https://github.com/nrfconnect/sdk-nrf/pull/4773#pullrequestreview-710815935.

**Comment by ppryga** [comment]
Closing this PR due to consolidation with #578.

**Pull request closed without merging**
