### PR TITLE
[nrf fromtree] west.yml: Update hal_nordic revision

### PR DESCRIPTION
**Pull request by rlubos**
This patch fixes bugs in the ieee802154 radio driver

Signed-off-by: Jedrzej Ciupis <jedrzej.ciupis@nordicsemi.no>

### CODE REVIEW

**Comment by rlubos** [comment]
The manifest update introduces 3 bugfix commits for the 802.15.4 radio driver.

**Comment by rlubos** [comment]
Manifest update: https://github.com/nrfconnect/sdk-nrf/pull/3087

**Review by hubertmis — APPROVED** [review]

**Review by hubertmis — APPROVED** [review]

**Comment by rlubos** [comment]
@carlescufi @tejlmand Could we get this one in? The manifest update PR is green.

**Comment by rlubos** [comment]
Btw, no clue why the CI is not running for this PR...

**Review by carlescufi — CHANGES_REQUESTED** [review]
`[nrf fromtree]`, no underscore

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
