### PR TITLE
Bluetooth: Post-upmerge bugfixes for v1.5

### PR DESCRIPTION
**Pull request by trond-snekvik**
Pulls in 3 Bluetooth Mesh bugfix PRs and one controller bugfix PR from upstream:
- zephyrproject-rtos/zephyr#32069 (merged upstream)
- zephyrproject-rtos/zephyr#31909 (merged upstream)
- zephyrproject-rtos/zephyr#32080 (merged upstream)
- zephyrproject-rtos/zephyr#32160 (merged upstream)

### CODE REVIEW

**Review by PavelVPV — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]

**Comment by trond-snekvik** [comment]
Compliance failures are all on commit title length.

**Comment by joerchan** [comment]
> Compliance failures are all on commit title length.

I usually do this, I think everyone else does too.
```
[nrf tag] long commit title that did not fit into the compliance ...

together with the nrf tag
```

**Review by joerchan — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]
> Pulls in 3 Bluetooth Mesh bugfix PRs and one controller bugfix PR from upstream:
> 
>     * [zephyrproject-rtos/zephyr#32069](https://github.com/zephyrproject-rtos/zephyr/pull/32069) (merged upstream)
> 
>     * [zephyrproject-rtos/zephyr#31909](https://github.com/zephyrproject-rtos/zephyr/pull/31909) (merged upstream)
> 
>     * [zephyrproject-rtos/zephyr#32080](https://github.com/zephyrproject-rtos/zephyr/pull/32080) (pending upstream)
> 
>     * [zephyrproject-rtos/zephyr#32160](https://github.com/zephyrproject-rtos/zephyr/pull/32160) (pending upstream)

Note, all PRs mentioned have been merged upstream, so you may change all the commits in this PR to `[nrf fromtree]`

**Comment by tejlmand** [comment]
> Compliance failures are all on commit title length.

you can still line wrap the title as it is done in other commits.
https://github.com/nrfconnect/sdk-zephyr/commit/a7ebc9d4577dbda0e380d19092ec6ff923eac889

Merging a PR with compliance failure causes all later PRs to fail in same way.
That has happened before.

**Review by tejlmand — CHANGES_REQUESTED** [review]
Please fix title length, so we don't end in the situation where all subsequent PRs starts to fail compliance.

**Review by tejlmand — APPROVED** [review]

**Review by tejlmand — CHANGES_REQUESTED** [review]
Included in #459

**Pull request closed without merging**
