### PR TITLE
[nrf fromtree] LE Audio: Cherry pick bugfixes for BAP

### PR DESCRIPTION
**Pull request by alexsven**
Some bugfixes for BAP related code are needed for nrf/applications/nrf5340_audio

### CODE REVIEW

**Comment by Thalley** [comment]
Suggest to also grab https://github.com/zephyrproject-rtos/zephyr/pull/47679

**Comment by alexsven** [comment]
> Suggest to also grab [zephyrproject-rtos/zephyr#47679](https://github.com/zephyrproject-rtos/zephyr/pull/47679)

Thank you, I've included that one as well

**Review by alwa-nordic — APPROVED** [review]

**Review by Thalley — APPROVED** [review]
Keep an eye on https://github.com/zephyrproject-rtos/zephyr/pull/48355 and https://github.com/zephyrproject-rtos/zephyr/pull/48354 as they may also provide some fixes for some issues when merged

**Comment by alexsven** [comment]
> Keep an eye on [zephyrproject-rtos/zephyr#48355](https://github.com/zephyrproject-rtos/zephyr/pull/48355) and [zephyrproject-rtos/zephyr#48354](https://github.com/zephyrproject-rtos/zephyr/pull/48354) as they may also provide some fixes for some issues when merged

Thank you. At this point I think should rather hope that they are merged before UM2 starts the 3rd of August

**Pull request merged**
