### PR TITLE
[nrf fromtree] net: Add copying of missing flags inside clone_pkt_attributes()

### PR DESCRIPTION
**Pull request by MarGasiorek**
The PR is cleaning code around flags in net_pkt structure, adds copying of missing flags inside clone_pkt_attributes() and included also additional test for flags copy functionality.

### CODE REVIEW

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Comment by de-nordic** [comment]
Rebase or close.

**Comment by MarGasiorek** [comment]
> Rebase or close.

Done

**Comment by glarsennordic** [comment]
LGTM, but I don't think any of the affected code is under my ownership

**Comment by MarGasiorek** [comment]
Is seems that changes are merged.

**Pull request closed without merging**
