### PR TITLE
[nrf noup] drivers: entropy: Switch entropy driver in nRF54L20

### PR DESCRIPTION
**Pull request by e-rk**
nrf-squash! [nrf noup] entropy: Add fake entropy nRF PRNG driver

Change psa driver to nordic entropy. nRF54L20 needs it as well as nRF54H20.

### CODE REVIEW

**Review by masz-nordic — APPROVED** [review]

**Review by pdunaj — CHANGES_REQUESTED** [review]
Why would nrf54h20 use fake entropy?

**Review by pdunaj — APPROVED** [review]
This is L20 not H20.

**Comment by e-rk** [comment]
> Why would nrf54h20 use fake entropy?

This is nRF54L20, not nRF54H20. Also PSA entropy does not work on nRF54L20 yet IIRC. Without this, many samples we need for testing don't build.

**Comment by pdunaj** [comment]
> > Why would nrf54h20 use fake entropy?
> 
> This is nRF54L20, not nRF54H20. Also PSA entropy does not work on nRF54L20 yet IIRC. Without this, many samples we need for testing don't build.

got it :)

**Review by Vge0rge — APPROVED** [review]

**Pull request merged**
