### PR TITLE
Ncs 2.4 rc2 rebase

### PR DESCRIPTION
**Pull request by de-nordic**

### CODE REVIEW

**Comment by rlubos** [comment]
The diff is not empty between rebase branch and main:
https://github.com/de-nordic/sdk-zephyr/compare/ncs-2.4-rc2-rebase..nrfconnect:main
Are the most recent commits missing?

**Review by rlubos — APPROVED** [review]
Diff is empty now.

**Review by rlubos — APPROVED** [review]
Diff is empty now.

**Comment by anangl** [comment]
The following commits should be squashed:
- aaec66c58665fae24aec362e94f74edffd809447 with 12f094599b6d510a735d0538ad33b0bc8e707f9f
- adf4154a39d24c3bfb5c3f5e2fecbfb372ef261a with 1ff4bec9b5f685b52448a798c93b2be1b0b545d9

And it looks like 44beb682ac50d85273886f8e248f65c95568b7e6 is missing a "cherry picked" entry referencing acb96b140c95e933546acc41cc6df22b609342db.

**Comment by de-nordic** [comment]
> The following commits should be squashed:
> 
>     * [aaec66c](https://github.com/nrfconnect/sdk-zephyr/commit/aaec66c58665fae24aec362e94f74edffd809447) with [12f0945](https://github.com/nrfconnect/sdk-zephyr/commit/12f094599b6d510a735d0538ad33b0bc8e707f9f)
> 
>     * [adf4154](https://github.com/nrfconnect/sdk-zephyr/commit/adf4154a39d24c3bfb5c3f5e2fecbfb372ef261a) with [1ff4bec](https://github.com/nrfconnect/sdk-zephyr/commit/1ff4bec9b5f685b52448a798c93b2be1b0b545d9)
> 
> 
> And it looks like [44beb68](https://github.com/nrfconnect/sdk-zephyr/commit/44beb682ac50d85273886f8e248f65c95568b7e6) is missing a "cherry picked" entry referencing [acb96b1](https://github.com/nrfconnect/sdk-zephyr/commit/acb96b140c95e933546acc41cc6df22b609342db).

@anangl I have fixed mentioned issues.

**Review by anangl — APPROVED** [review]

**Review by ns-tolu — APPROVED** [review]

**Pull request merged**
